/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Inventario;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author David
 */
public class Dialogo_Buscar_Inventario extends javax.swing.JDialog {

    /**
     * Creates new form Dialogo_Buscar_Cliente
     */
    public Dialogo_Buscar_Inventario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.tabla_Inventario.getTableHeader().setFont( new Font( "Arial", Font.BOLD, 13 ) );
        this.tabla_Inventario.getTableHeader().setBackground( new Color( 32, 136, 203 ));
        this.tabla_Inventario.getTableHeader().setForeground( new Color( 255, 255, 255)); 
        this.barra.setVisible(false);
        this.tabla_Inventario.getTableHeader().setReorderingAllowed(false) ;
        this.boton_Nuevo_Producto.setVisible(false);
        this.campo_Buscar.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_Botones = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Inventario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        campo_Buscar = new javax.swing.JTextField();
        barra = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        boton_Nuevo_Producto = new javax.swing.JButton();
        combo_Opciones = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar inventario");
        setMaximumSize(new java.awt.Dimension(908, 420));
        setMinimumSize(new java.awt.Dimension(908, 420));
        setPreferredSize(new java.awt.Dimension(908, 420));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_Inventario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabla_Inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Proveedor", "Disponible", "P. Compra", "P. Venta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_Inventario);
        if (tabla_Inventario.getColumnModel().getColumnCount() > 0) {
            tabla_Inventario.getColumnModel().getColumn(3).setPreferredWidth(20);
            tabla_Inventario.getColumnModel().getColumn(4).setPreferredWidth(20);
            tabla_Inventario.getColumnModel().getColumn(5).setPreferredWidth(20);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 158, 840, 210));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Buscar:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 71, -1, -1));

        campo_Buscar.setEditable(false);
        campo_Buscar.setBackground(new java.awt.Color(255, 255, 255));
        campo_Buscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Buscar.setMaximumSize(new java.awt.Dimension(2, 20));
        campo_Buscar.setMinimumSize(new java.awt.Dimension(2, 20));
        campo_Buscar.setPreferredSize(new java.awt.Dimension(2, 20));
        campo_Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_BuscarKeyTyped(evt);
            }
        });
        getContentPane().add(campo_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 70, 390, 23));

        barra.setBackground(new java.awt.Color(255, 255, 255));
        barra.setFloatable(false);
        barra.setRollover(true);
        barra.setMaximumSize(new java.awt.Dimension(797, 40));
        barra.setMinimumSize(new java.awt.Dimension(797, 40));
        barra.setPreferredSize(new java.awt.Dimension(797, 40));
        barra.add(jSeparator1);

        boton_Nuevo_Producto.setBackground(new java.awt.Color(255, 255, 255));
        boton_Nuevo_Producto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Nuevo_Producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/producto.png"))); // NOI18N
        boton_Nuevo_Producto.setText("Nuevo producto");
        boton_Nuevo_Producto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Nuevo_Producto.setMaximumSize(new java.awt.Dimension(140, 40));
        boton_Nuevo_Producto.setMinimumSize(new java.awt.Dimension(140, 40));
        boton_Nuevo_Producto.setPreferredSize(new java.awt.Dimension(140, 40));
        barra.add(boton_Nuevo_Producto);

        getContentPane().add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 910, 40));

        combo_Opciones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combo_Opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar.....", "Por Codigo", "Por Descripcion", "Por Proveedor" }));
        combo_Opciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(combo_Opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 170, 24));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagen-fondo-aurora-celeste_1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_BuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_BuscarKeyTyped
        
    }//GEN-LAST:event_campo_BuscarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Buscar_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Buscar_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Buscar_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Buscar_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dialogo_Buscar_Inventario dialog = new Dialogo_Buscar_Inventario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JToolBar barra;
    public javax.swing.JButton boton_Nuevo_Producto;
    public javax.swing.JTextField campo_Buscar;
    public javax.swing.JComboBox<String> combo_Opciones;
    public javax.swing.ButtonGroup grupo_Botones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    public javax.swing.JTable tabla_Inventario;
    // End of variables declaration//GEN-END:variables
}
