/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Pagos;

import Modelo.Rol;
import Modelo.Usuario;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author David
 */
public class Panel_Pagos extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Estado_De_Cuenta
     */
    public Panel_Pagos() {
        initComponents();
        this.boton_Reporte.setEnabled(false);
        this.combo_Opcion.setEnabled(false);
        tabla_Estado_Pagos.getTableHeader().setFont( new Font( "Arial", Font.BOLD, 12 ) );
        tabla_Estado_Pagos.getTableHeader().setBackground( new Color( 32, 136, 203 ) );
        tabla_Estado_Pagos.getTableHeader().setForeground( new Color( 255, 255, 255) );
        tabla_Estado_Pagos.getTableHeader().setFont( new Font( "Arial", Font.BOLD, 12 ) );
        tabla_Estado_Pagos.getTableHeader().setBackground( new Color( 32, 136, 203 ) );
        tabla_Estado_Pagos.getTableHeader().setForeground( new Color( 255, 255, 255) );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        boton_Buscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        boton_Reporte = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_Estado_Pagos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        combo_Proveedor = new javax.swing.JTextField();
        campo_RUC = new javax.swing.JTextField();
        campo_Direccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campo_Telefono = new javax.swing.JTextField();
        campo_Correo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        combo_Opcion = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        boton_Cerrar_Sesion = new javax.swing.JButton();
        etiqueta_Rol = new javax.swing.JLabel();
        etiqueta_Nombre_Usuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.activeCaption);
        setMaximumSize(new java.awt.Dimension(1400, 800));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setPreferredSize(new java.awt.Dimension(1400, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        boton_Buscar.setBackground(new java.awt.Color(255, 255, 255));
        boton_Buscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        boton_Buscar.setText("Buscar");
        boton_Buscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Buscar.setFocusable(false);
        boton_Buscar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Buscar.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Buscar.setMinimumSize(new java.awt.Dimension(100, 37));
        boton_Buscar.setPreferredSize(new java.awt.Dimension(100, 37));
        jToolBar1.add(boton_Buscar);
        jToolBar1.add(jSeparator1);

        boton_Reporte.setBackground(new java.awt.Color(255, 255, 255));
        boton_Reporte.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportar 1.png"))); // NOI18N
        boton_Reporte.setText("Reporte");
        boton_Reporte.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Reporte.setFocusable(false);
        boton_Reporte.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Reporte.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Reporte.setMinimumSize(new java.awt.Dimension(100, 37));
        boton_Reporte.setPreferredSize(new java.awt.Dimension(100, 37));
        jToolBar1.add(boton_Reporte);

        add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 40));

        tabla_Estado_Pagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tabla_Estado_Pagos);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 1080, 310));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Proveedor:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        combo_Proveedor.setEditable(false);
        combo_Proveedor.setBackground(new java.awt.Color(255, 255, 255));
        combo_Proveedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combo_Proveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(combo_Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 320, 22));

        campo_RUC.setEditable(false);
        campo_RUC.setBackground(new java.awt.Color(255, 255, 255));
        campo_RUC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_RUC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_RUC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_RUCKeyTyped(evt);
            }
        });
        add(campo_RUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 150, 22));

        campo_Direccion.setEditable(false);
        campo_Direccion.setBackground(new java.awt.Color(255, 255, 255));
        campo_Direccion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Direccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_DireccionKeyTyped(evt);
            }
        });
        add(campo_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 560, 22));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Direccion:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Telefono:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        campo_Telefono.setEditable(false);
        campo_Telefono.setBackground(new java.awt.Color(255, 255, 255));
        campo_Telefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Telefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_TelefonoKeyTyped(evt);
            }
        });
        add(campo_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 230, 22));

        campo_Correo.setEditable(false);
        campo_Correo.setBackground(new java.awt.Color(255, 255, 255));
        campo_Correo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Correo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_CorreoKeyTyped(evt);
            }
        });
        add(campo_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 230, 22));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Correo:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        combo_Opcion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combo_Opcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar......", "Todos", "Por pagar", "Pagado", "Anulado" }));
        add(combo_Opcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 200, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Estado:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("RUC:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));

        boton_Cerrar_Sesion.setBackground(new java.awt.Color(255, 255, 255));
        boton_Cerrar_Sesion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Cerrar_Sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit-32.png"))); // NOI18N
        boton_Cerrar_Sesion.setText("Cerrar");
        boton_Cerrar_Sesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(boton_Cerrar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 120, 40));

        etiqueta_Rol.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiqueta_Rol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(etiqueta_Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(1134, 20, 147, 20));

        etiqueta_Nombre_Usuario.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiqueta_Nombre_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        etiqueta_Nombre_Usuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        etiqueta_Nombre_Usuario.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(etiqueta_Nombre_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 180, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo blanco.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 180, 40));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Informacion proveedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 1150, 240));

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Compras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 1150, 380));
    }// </editor-fold>//GEN-END:initComponents

    private void campo_RUCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_RUCKeyTyped
        char c = evt.getKeyChar();
        if( c < '0'  || c > '9' || this.campo_RUC.getText().length() >= 13 ) evt.consume();
    }//GEN-LAST:event_campo_RUCKeyTyped

    private void campo_DireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_DireccionKeyTyped
        char c = evt.getKeyChar();
        if( c == evt.VK_SPACE && this.campo_Direccion.getText().length() == 0 ) evt.consume();
        else if(  ( c < 'a' || c > 'z' ) && ( c < 'A' || c>'Z' ) && ( c < '0' || c > '9' ) && ( c < '-' || c > '.' ) && c != evt.VK_SPACE ){
            evt.consume();
        }
    }//GEN-LAST:event_campo_DireccionKeyTyped

    private void campo_TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_TelefonoKeyTyped
        char c = evt.getKeyChar();
        if( c < '0'  || c > '9' || this.campo_Telefono.getText().length() >= 9 ) evt.consume();
    }//GEN-LAST:event_campo_TelefonoKeyTyped

    private void campo_CorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_CorreoKeyTyped
        char c = evt.getKeyChar();
        if ( ( c < 'a' || c > 'z' ) && ( c < 'A' || c >'Z' ) && ( c < '0'  || c > '9' ) && ( c < '#' || c > '&' ) && ( c < '-' || c > '/' ) &&  (  c == evt.VK_SPACE || this.campo_Correo.getText().contains( "@" ) ) ) evt.consume();
    }//GEN-LAST:event_campo_CorreoKeyTyped

    public void valores_Proveedores(String proveedor, String direccion, String telefono, String correo, String RUC) {
        this.combo_Proveedor.setText(proveedor);
        this.campo_Direccion.setText(direccion);
        this.campo_Telefono.setText(telefono);
        this.campo_Correo.setText(correo);
        this.campo_RUC.setText(RUC);
        this.combo_Opcion.setSelectedItem("Seleccionar......");
    }
    
    public void activar_Botones(boolean bandera1, boolean bandera2){
        this.boton_Buscar.setEnabled(bandera1);
        this.combo_Opcion.setEnabled(bandera2);
    }
    
    public void set_Usuario(Usuario usuario, String rol){
        this.etiqueta_Nombre_Usuario.setText(usuario.getNombre() + " " + usuario.getApellido());
        this.etiqueta_Rol.setText(rol);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton boton_Buscar;
    public javax.swing.JButton boton_Cerrar_Sesion;
    public javax.swing.JButton boton_Reporte;
    public javax.swing.JTextField campo_Correo;
    public javax.swing.JTextField campo_Direccion;
    public javax.swing.JTextField campo_RUC;
    public javax.swing.JTextField campo_Telefono;
    public javax.swing.JComboBox<String> combo_Opcion;
    public javax.swing.JTextField combo_Proveedor;
    public javax.swing.JLabel etiqueta_Nombre_Usuario;
    public javax.swing.JLabel etiqueta_Rol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JTable tabla_Estado_Pagos;
    // End of variables declaration//GEN-END:variables
}
