/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Cliente;

import Controlador.PlaceHolder_Textos;
import Modelo.Usuario;
import java.text.DecimalFormat;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author David
 */
public class Panel_Clientes extends javax.swing.JPanel {

    PlaceHolder_Textos textos_Place;

    /**
     * Creates new form Panel_Clientes
     */
    public Panel_Clientes() {
        initComponents();
        this.grupo_Botones_DNI.add(this.radio_Boton_CI);
        this.grupo_Botones_DNI.add(this.radio_Boton_RUC);
        this.campo_RUC.setEditable(false);
        this.textos_Place = new PlaceHolder_Textos("Nombre cliente", this.combo_Cliente);
        this.textos_Place = new PlaceHolder_Textos("172004xxxxxxx", this.campo_RUC);
        this.textos_Place = new PlaceHolder_Textos("Av principal OE7-489", this.campo_Direccion);
        this.textos_Place = new PlaceHolder_Textos("023005698", this.campo_Telefono);
        this.textos_Place = new PlaceHolder_Textos("0986035281", this.campo_Celular);
        this.textos_Place = new PlaceHolder_Textos("empresa@dominio.com", this.campo_Correo);
        this.textos_Place = new PlaceHolder_Textos("Alexander Lopez", this.campo_Contacto);
        this.etiqueta_Indicador_Ciudad.setVisible(false);
        this.etiqueta_Indicador_RUC.setVisible(false);
        this.etiqueta_Indicador_Direccion.setVisible(false);
        this.etiqueta_Indicador_Telefono.setVisible(false);
        this.etiqueta_Indicador_Celular.setVisible(false);
        this.etiqueta_Indicador_Correo.setVisible(false);
        this.etiqueta_Indicador_Contacto.setVisible(false);
        this.etiqueta_Indicador_Cliente.setVisible(false);
        this.boton_Modificar.setEnabled(false);
        this.boton_Eliminar.setEnabled(false);
        this.etiqueta_Correccion_RUC.setVisible(false);
        this.etiqueta_Correccion_Correo.setVisible(false);
        AutoCompleteDecorator.decorate(this.campo_Ciudad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_Botones_DNI = new javax.swing.ButtonGroup();
        etiqueta_Cliente = new javax.swing.JLabel();
        etiqueta_Ciudad = new javax.swing.JLabel();
        etiqueta_RUC = new javax.swing.JLabel();
        campo_RUC = new javax.swing.JTextField();
        etiqueta_Direccion = new javax.swing.JLabel();
        campo_Direccion = new javax.swing.JTextField();
        campo_Telefono = new javax.swing.JTextField();
        etiqueta_Telefono = new javax.swing.JLabel();
        etiqueta_Correo = new javax.swing.JLabel();
        campo_Correo = new javax.swing.JTextField();
        campo_Contacto = new javax.swing.JTextField();
        etiqueta_Persona1 = new javax.swing.JLabel();
        etiqueta_Persona2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campo_Celular = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        boton_Nuevo_Cliente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        boton_Agregar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        boton_Modificar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        boton_Eliminar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        boton_Reportes_Clientes = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        etiqueta_Indicador_Direccion = new javax.swing.JLabel();
        etiqueta_Indicador_Telefono = new javax.swing.JLabel();
        etiqueta_Indicador_Ciudad = new javax.swing.JLabel();
        etiqueta_Indicador_Celular = new javax.swing.JLabel();
        etiqueta_Indicador_Correo = new javax.swing.JLabel();
        etiqueta_Indicador_RUC = new javax.swing.JLabel();
        etiqueta_Indicador_Contacto = new javax.swing.JLabel();
        boton_Buscar = new javax.swing.JButton();
        combo_Cliente = new javax.swing.JTextField();
        etiqueta_Indicador_Cliente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        boton_Cerrar_Sesion = new javax.swing.JButton();
        campo_Cod_Cliente = new javax.swing.JTextField();
        radio_Boton_CI = new javax.swing.JRadioButton();
        radio_Boton_RUC = new javax.swing.JRadioButton();
        campo_Ciudad = new javax.swing.JComboBox<>();
        etiqueta_Nombre_Usuario = new javax.swing.JLabel();
        etiqueta_Rol = new javax.swing.JLabel();
        etiqueta_Correccion_RUC = new javax.swing.JLabel();
        etiqueta_Correccion_Correo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.activeCaption);
        setMaximumSize(new java.awt.Dimension(1400, 800));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setPreferredSize(new java.awt.Dimension(1400, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiqueta_Cliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Cliente.setText("Cliente:");
        add(etiqueta_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        etiqueta_Ciudad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Ciudad.setText("Ciudad:");
        add(etiqueta_Ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        etiqueta_RUC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_RUC.setText("R.U.C/ CI:");
        add(etiqueta_RUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        campo_RUC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_RUC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_RUC.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        campo_RUC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_RUCKeyTyped(evt);
            }
        });
        add(campo_RUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 210, 22));

        etiqueta_Direccion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Direccion.setText("Direccion:");
        add(etiqueta_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        campo_Direccion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Direccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_DireccionKeyTyped(evt);
            }
        });
        add(campo_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 330, 22));

        campo_Telefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Telefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_TelefonoKeyTyped(evt);
            }
        });
        add(campo_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 180, 22));

        etiqueta_Telefono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Telefono.setText("Telefono:");
        add(etiqueta_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, -1, -1));

        etiqueta_Correo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Correo.setText("Correo:");
        add(etiqueta_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 640, -1, -1));

        campo_Correo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Correo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_CorreoKeyTyped(evt);
            }
        });
        add(campo_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 640, 315, 22));

        campo_Contacto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Contacto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Contacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_ContactoKeyTyped(evt);
            }
        });
        add(campo_Contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, 260, 22));

        etiqueta_Persona1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        etiqueta_Persona1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Persona1.setText("Persona de");
        add(etiqueta_Persona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, -1, 20));

        etiqueta_Persona2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        etiqueta_Persona2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Persona2.setText(" contacto:");
        add(etiqueta_Persona2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Celular:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        campo_Celular.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Celular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Celular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_CelularKeyTyped(evt);
            }
        });
        add(campo_Celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 157, 22));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        boton_Nuevo_Cliente.setBackground(new java.awt.Color(255, 255, 255));
        boton_Nuevo_Cliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Nuevo_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-archivo.png"))); // NOI18N
        boton_Nuevo_Cliente.setText("Nuevo");
        boton_Nuevo_Cliente.setToolTipText("Nuevo cliente");
        boton_Nuevo_Cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Nuevo_Cliente.setFocusable(false);
        boton_Nuevo_Cliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Nuevo_Cliente.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Nuevo_Cliente.setMinimumSize(new java.awt.Dimension(100, 37));
        boton_Nuevo_Cliente.setPreferredSize(new java.awt.Dimension(100, 37));
        boton_Nuevo_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Nuevo_ClienteActionPerformed(evt);
            }
        });
        jToolBar1.add(boton_Nuevo_Cliente);

        jSeparator1.setBackground(java.awt.SystemColor.textHighlight);
        jToolBar1.add(jSeparator1);

        boton_Agregar.setBackground(java.awt.Color.white);
        boton_Agregar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton-anadir-usuario (1).png"))); // NOI18N
        boton_Agregar.setText("Guardar");
        boton_Agregar.setToolTipText("Guardar cliente");
        boton_Agregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Agregar.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Agregar.setMinimumSize(new java.awt.Dimension(100, 37));
        boton_Agregar.setPreferredSize(new java.awt.Dimension(100, 37));
        boton_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_AgregarActionPerformed(evt);
            }
        });
        jToolBar1.add(boton_Agregar);
        jToolBar1.add(jSeparator2);

        boton_Modificar.setBackground(java.awt.Color.white);
        boton_Modificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar-documento.png"))); // NOI18N
        boton_Modificar.setText("Modificar");
        boton_Modificar.setToolTipText("Modificar cliente");
        boton_Modificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Modificar.setMaximumSize(new java.awt.Dimension(105, 37));
        boton_Modificar.setMinimumSize(new java.awt.Dimension(60, 37));
        boton_Modificar.setPreferredSize(new java.awt.Dimension(60, 37));
        jToolBar1.add(boton_Modificar);
        jToolBar1.add(jSeparator3);

        boton_Eliminar.setBackground(java.awt.Color.white);
        boton_Eliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton-eliminar.png"))); // NOI18N
        boton_Eliminar.setText("Eliminar");
        boton_Eliminar.setToolTipText("Eliminar cliente");
        boton_Eliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Eliminar.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Eliminar.setMinimumSize(new java.awt.Dimension(60, 37));
        boton_Eliminar.setPreferredSize(new java.awt.Dimension(60, 37));
        jToolBar1.add(boton_Eliminar);
        jToolBar1.add(jSeparator4);

        boton_Reportes_Clientes.setBackground(new java.awt.Color(255, 255, 255));
        boton_Reportes_Clientes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Reportes_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportar.png"))); // NOI18N
        boton_Reportes_Clientes.setText("Reporte");
        boton_Reportes_Clientes.setToolTipText("Reporte cliente");
        boton_Reportes_Clientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Reportes_Clientes.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Reportes_Clientes.setMinimumSize(new java.awt.Dimension(60, 37));
        boton_Reportes_Clientes.setPreferredSize(new java.awt.Dimension(60, 37));
        jToolBar1.add(boton_Reportes_Clientes);
        jToolBar1.add(jSeparator5);

        add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 40));

        etiqueta_Indicador_Direccion.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Direccion.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Direccion.setText("*");
        add(etiqueta_Indicador_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, -1, -1));

        etiqueta_Indicador_Telefono.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Telefono.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Telefono.setText("*");
        add(etiqueta_Indicador_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, -1, -1));

        etiqueta_Indicador_Ciudad.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Ciudad.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Ciudad.setText("*");
        add(etiqueta_Indicador_Ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        etiqueta_Indicador_Celular.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Celular.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Celular.setText("*");
        add(etiqueta_Indicador_Celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, -1, -1));

        etiqueta_Indicador_Correo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Correo.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Correo.setText("*");
        add(etiqueta_Indicador_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 640, 20, -1));

        etiqueta_Indicador_RUC.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_RUC.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_RUC.setText("*");
        add(etiqueta_Indicador_RUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));

        etiqueta_Indicador_Contacto.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Contacto.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Contacto.setText("*");
        add(etiqueta_Indicador_Contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, -1, -1));

        boton_Buscar.setBackground(java.awt.Color.white);
        boton_Buscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar-en-carpeta.png"))); // NOI18N
        boton_Buscar.setToolTipText("Buscar cliente");
        boton_Buscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Buscar.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Buscar.setMinimumSize(new java.awt.Dimension(100, 37));
        boton_Buscar.setPreferredSize(new java.awt.Dimension(100, 37));
        add(boton_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 50, -1));

        combo_Cliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combo_Cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(combo_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 330, 22));

        etiqueta_Indicador_Cliente.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Cliente.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Cliente.setText("*");
        add(etiqueta_Indicador_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Cod. Cliente:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        boton_Cerrar_Sesion.setBackground(new java.awt.Color(255, 255, 255));
        boton_Cerrar_Sesion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Cerrar_Sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit-32.png"))); // NOI18N
        boton_Cerrar_Sesion.setText("Cerrar");
        boton_Cerrar_Sesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(boton_Cerrar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 120, 40));

        campo_Cod_Cliente.setEditable(false);
        campo_Cod_Cliente.setBackground(new java.awt.Color(255, 255, 255));
        campo_Cod_Cliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Cod_Cliente.setForeground(new java.awt.Color(0, 51, 255));
        campo_Cod_Cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(campo_Cod_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 170, 22));

        radio_Boton_CI.setBackground(new java.awt.Color(255, 255, 255));
        radio_Boton_CI.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        radio_Boton_CI.setText("Cedula");
        radio_Boton_CI.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        radio_Boton_CI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_Boton_CIActionPerformed(evt);
            }
        });
        add(radio_Boton_CI, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 272, -1, -1));

        radio_Boton_RUC.setBackground(new java.awt.Color(255, 255, 255));
        radio_Boton_RUC.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        radio_Boton_RUC.setText("RUC");
        radio_Boton_RUC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        radio_Boton_RUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_Boton_RUCActionPerformed(evt);
            }
        });
        add(radio_Boton_RUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        campo_Ciudad.setEditable(true);
        campo_Ciudad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Ciudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuenca", "Camilo Ponce Enríquez", "Chordeleg", "El Pan", "Girón", "Guachapala", "Gualaceo", "Nabón", "Oña", "Paute", "Pucará", "San Fernando", "Santa Isabel", "Sevilla de Oro", "Sígsig", "Guaranda", "Caluma", "Chillanes", "Chimbo", "Echeandía", "Las Naves", "San Miguel", "Cantón Azogues", "Biblián", "Cañar", "Déleg", "El Tambo", "La Troncal", "Suscal", "Tulcán", "Bolívar", "Espejo", "Mira", "Montúfar", "Huaca", "Riobamba", "Alausí", "Chambo", "Chunchi", "Colta", "Cumandá", "Guamote", "Guano", "Pallatanga", "Penipe", "Latacunga", "La Maná", "Pangua", "Pujilí", "Salcedo", "Saquisilí", "Sigchos", "Machala", "Arenillas", "Atahualpa", "Balsas", "Chilla", "El Guabo", "Huaquillas", "Las Lajas", "Marcabelí", "Pasaje", "Piñas", "Portovelo", "Santa Rosa", "Zaruma", "Esmeraldas", "Atacames", "Eloy Alfaro", "Muisne", "Quinindé", "Rioverde", "San Lorenzo", "San Cristóbal", "Isabela", "Santa Cruz", "Guayaquil", "Alfredo Baquerizo", "Balao", "Balzar", "Colimes", "Daule", "Durán", "El Empalme", "El Triunfo", "General Antonio Elizalde", "Isidro Ayora", "Lomas de Sargentillo", "Marcelino Maridueña", "Milagro", "Naranjal", "Naranjito", "Ibarra", "Antonio Ante", "Cotacachi", "Otavalo", "Pimampiro", "San Miguel de Urcuquí", "Loja", "Calvas", "Catamayo", "Celica", "Chaguarpamba", "Espíndola", "Gonzanamá", "Macará", "Olmedo", "Paltas", "Pindal", "Puyango", "Quilanga", "Saraguro", "Sozoranga", "Zapotillo", "Babahoyo", "Baba", "Buena Fe", "Mocache", "Montalvo", "Palenque", "Puebloviejo", "Quevedo", "Quinsaloma", "Urdaneta", "Valencia", "Ventanas", "Vinces", "Portoviejo", "24 de Mayo", "Bolívar", "Chone", "El Carmen", "Flavio Alfaro", "Jama", "Jaramijó", "Jipijapa", "Junín", "Manta", "Montecristi", "Olmedo", "Paján", "Pedernales", "Pichincha", "Puerto López", "Rocafuerte", "San Vicente", "Santa Ana", "Sucre", "Tosagua", "Morona", "Gualaquiza", "Huamboya", "Limón Indanza", "Logroño", "Pablo Sexto", "Palora", "San Juan Bosco", "Santiago de Méndez", "Sucúa", "Taisha", "Tiwintza", "Tena", "Archidona", "Carlos Julio Arosemena Tola", "El Chaco", "Quijos", "Francisco de Orellana", "Aguarico", "La Joya de los Sachas", "Loreto", "Pastaza", "Arajuno", "Mera", "Santa Clara", "Quito", "Cayambe", "Mejía", "Pedro Moncayo", "Pedro Vicente Maldonado", "Puerto Quito", "Rumiñahui", "San Miguel de los Bancos", "Santa Elena", "La Libertad", "Salinas", "Santo Domingo", "La Concordia", "Lago Agrio", "Cascales", "Cuyabeno", "Gonzalo Pizarro", "Putumayo", "Shushufindi", "Sucumbíos", "Ambato", "Baños", "Cevallos", "Mocha", "Patate", "Quero", "San Pedro de Pelileo", "Santiago de Píllaro", "Tisaleo", "Zamora", "Centinela del Cóndor", "Chinchipe", "El Pangui", "Nangaritza", "Palanda", "Paquisha", "Yacuambi", "Yantzaza", "Nobol", "Palestina", "Pedro Carbo", "Playas", "Salitre", "Samborondón", "Santa Lucía", "Simón Bolívar", "Yaguachi" }));
        add(campo_Ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 180, 22));

        etiqueta_Nombre_Usuario.setBackground(new java.awt.Color(255, 255, 255));
        etiqueta_Nombre_Usuario.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiqueta_Nombre_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        etiqueta_Nombre_Usuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        etiqueta_Nombre_Usuario.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(etiqueta_Nombre_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 180, 40));

        etiqueta_Rol.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiqueta_Rol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(etiqueta_Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(1133, 20, 149, 20));

        etiqueta_Correccion_RUC.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        etiqueta_Correccion_RUC.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Correccion_RUC.setText("El RUC/CI ya se encuentra registrado para otro cliente");
        add(etiqueta_Correccion_RUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 310, -1));

        etiqueta_Correccion_Correo.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        etiqueta_Correccion_Correo.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Correccion_Correo.setText("El Correo ya se encuentra registrado para otro cliente");
        add(etiqueta_Correccion_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 644, 310, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS CLIENTE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 18))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 1290, 640));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo blanco.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 180, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void boton_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_AgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_AgregarActionPerformed

    private void boton_Nuevo_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Nuevo_ClienteActionPerformed
        
    }//GEN-LAST:event_boton_Nuevo_ClienteActionPerformed

    private void campo_DireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_DireccionKeyTyped
        char c = evt.getKeyChar();
        if (c == evt.VK_SPACE && this.campo_Direccion.getText().length() == 0) {
            evt.consume();
        } else if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < '0' || c > '9') && (c < '-' || c > '.') && c != evt.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_DireccionKeyTyped

    private void campo_ContactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_ContactoKeyTyped
        char c = evt.getKeyChar();
        if (c == evt.VK_SPACE && this.campo_Contacto.getText().length() == 0) {
            evt.consume();
        } else if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && c != evt.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_ContactoKeyTyped

    private void campo_CorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_CorreoKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < '0' || c > '9') && (c < '#' || c > '&') && (c < '-' || c > '/') && (c == evt.VK_SPACE || this.campo_Correo.getText().contains("@"))) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_CorreoKeyTyped

    private void campo_RUCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_RUCKeyTyped
        char c = evt.getKeyChar();
        
        if (this.radio_Boton_RUC.isSelected()) {
            if (c < '0' || c > '9' || this.campo_RUC.getText().length() >= 13) {
                evt.consume();
            }
        }
        
        if (this.radio_Boton_CI.isSelected()) {
            if (c < '0' || c > '9' || this.campo_RUC.getText().length() >= 10) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_campo_RUCKeyTyped

    private void campo_TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_TelefonoKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9' || this.campo_Telefono.getText().length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_TelefonoKeyTyped

    private void campo_CelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_CelularKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9' || this.campo_Celular.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_CelularKeyTyped

    private void radio_Boton_CIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_Boton_CIActionPerformed
        this.campo_RUC.setEditable(true);
        this.campo_RUC.setText("");
    }//GEN-LAST:event_radio_Boton_CIActionPerformed

    private void radio_Boton_RUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_Boton_RUCActionPerformed
        this.campo_RUC.setEditable(true);
        this.campo_RUC.setText("");
    }//GEN-LAST:event_radio_Boton_RUCActionPerformed

    public boolean etiquetas() {
        boolean bandera = true;
        
        if (this.combo_Cliente.getText().isEmpty()) {
            this.etiqueta_Indicador_Cliente.setVisible(true);
            bandera = false;
        } else {
            this.etiqueta_Indicador_Cliente.setVisible(false);
        }

        if (this.campo_Ciudad.getSelectedIndex() == - 1) {
            this.etiqueta_Indicador_Ciudad.setVisible(true);
            bandera = false;
        } else {
            this.etiqueta_Indicador_Ciudad.setVisible(false);
        }

        if( this.campo_RUC.getText().matches( "[0-9][0-9]{12}" ) && this.radio_Boton_RUC.isSelected() ){
            this.etiqueta_Indicador_RUC.setVisible( false );
        }else if(this.campo_RUC.getText().matches( "[0-9][0-9]{9}" ) && this.radio_Boton_CI.isSelected()){
            this.etiqueta_Indicador_RUC.setVisible( false );
        }
        else{
            this.etiqueta_Indicador_RUC.setVisible( true );
            bandera = false;
        }

        if (this.campo_Direccion.getText().isEmpty()) {
            this.etiqueta_Indicador_Direccion.setVisible(true);
            bandera = false;
        } else {
            this.etiqueta_Indicador_Direccion.setVisible(false);
        }	

        if (this.campo_Telefono.getText().matches("[0][1-9][0-9]{7}")) {
            this.etiqueta_Indicador_Telefono.setVisible(false);
        } else {
            this.etiqueta_Indicador_Telefono.setVisible(true);
            bandera = false;
        }

        if (this.campo_Celular.getText().matches("[0][8-9][0-9]{8}")) {
            this.etiqueta_Indicador_Celular.setVisible(false);
        } else {
            this.etiqueta_Indicador_Celular.setVisible(true);
            bandera = false;
        }

        if (this.campo_Correo.getText().matches("[a-zA-Z_\\d]+@[a-zA-Z]+(\\.[a-zA-Z]*)+")) {
            this.etiqueta_Indicador_Correo.setVisible(false);
        } else {
            this.etiqueta_Indicador_Correo.setVisible(true);
            bandera = false;
        }

        if (this.campo_Contacto.getText().isEmpty()) {
            this.etiqueta_Indicador_Contacto.setVisible(true);
            bandera = false;
        } else {
            this.etiqueta_Indicador_Contacto.setVisible(false);
        }
        return bandera;
    }

    public void limpiar_Campos() {
        this.campo_Cod_Cliente.setText("");
        this.combo_Cliente.setText("");
        this.campo_Celular.setText("");
        this.campo_Ciudad.setSelectedIndex(0);
        this.campo_Contacto.setText("");
        this.campo_Correo.setText("");
        this.campo_Direccion.setText("");
        this.campo_RUC.setText("");
        this.campo_Telefono.setText("");
        this.grupo_Botones_DNI.clearSelection();
        this.campo_RUC.setEditable(false);
    }

    public void botones(boolean bandera1, boolean bandera2, boolean bandera3, boolean bandera4, boolean bandera5, boolean bandera6) {
        this.boton_Agregar.setEnabled(bandera1);
        this.boton_Nuevo_Cliente.setEnabled(bandera2);
        this.boton_Modificar.setEnabled(bandera3);
        this.boton_Eliminar.setEnabled(bandera4);
        this.boton_Reportes_Clientes.setEnabled(bandera6);
    }

    public void setCampos(String codigo, String nombre, String direccion, String RUC, String telefono, String ciudad, String persona, String celular, String correo) {
        this.botones(false, true, true, true, false, false);
        this.campo_Cod_Cliente.setText(String.valueOf(codigo));
        this.combo_Cliente.setText(nombre);
        this.campo_Direccion.setText(direccion);
        this.campo_RUC.setText(RUC);
        this.campo_Telefono.setText(telefono);
        this.campo_Ciudad.setSelectedItem(ciudad);
        this.campo_Contacto.setText(persona);
        this.campo_Celular.setText(celular);
        this.campo_Correo.setText(correo);
    }
    
    public void campos_Busqueda() {
        this.campo_RUC.setEditable(true);

        if (this.campo_RUC.getText().length() == 10) {
            this.radio_Boton_CI.setSelected(true);
        } else if (this.campo_RUC.getText().length() == 13) {
            this.radio_Boton_RUC.setSelected(true);
        }
    }
    
    public void limpiar_Etiquetas_Campos() {
        this.etiqueta_Indicador_Cliente.setVisible(false);
        this.etiqueta_Indicador_Ciudad.setVisible(false);
        this.etiqueta_Indicador_RUC.setVisible(false);
        this.etiqueta_Indicador_Direccion.setVisible(false);
        this.etiqueta_Indicador_Telefono.setVisible(false);
        this.etiqueta_Indicador_Celular.setVisible(false);
        this.etiqueta_Indicador_Correo.setVisible(false);
        this.etiqueta_Indicador_Contacto.setVisible(false);
        this.etiqueta_Correccion_RUC.setVisible(false);
        this.etiqueta_Correccion_Correo.setVisible(false);
    }
    
    public void set_Usuario(Usuario usuario, String rol){
        this.etiqueta_Nombre_Usuario.setText(usuario.getNombre() + " " + usuario.getApellido());
        this.etiqueta_Rol.setText(rol);
    }
    
    public void correccion_Campos(String valor){
        if(valor.equals(this.campo_RUC.getText())){
            this.etiqueta_Correccion_RUC.setVisible(true);
        }
        
        if(valor.equals(this.campo_Correo.getText())){
            this.etiqueta_Correccion_Correo.setVisible(true);
        }
    }
    
    public void numero_Cliente(String numero) {
        if (numero == null) {
            this.campo_Cod_Cliente.setText(convertirNumero(0));
        } else {
            this.campo_Cod_Cliente.setText(convertirNumero(Integer.parseInt(numero)));
        }
    }

    public String convertirNumero(int numero) {
        DecimalFormat format = new DecimalFormat("00000000");
        return format.format(Integer.valueOf(numero) + 1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton boton_Agregar;
    public javax.swing.JButton boton_Buscar;
    public javax.swing.JButton boton_Cerrar_Sesion;
    public javax.swing.JButton boton_Eliminar;
    public javax.swing.JButton boton_Modificar;
    public javax.swing.JButton boton_Nuevo_Cliente;
    public javax.swing.JButton boton_Reportes_Clientes;
    public javax.swing.JTextField campo_Celular;
    public javax.swing.JComboBox<String> campo_Ciudad;
    public javax.swing.JTextField campo_Cod_Cliente;
    public javax.swing.JTextField campo_Contacto;
    public javax.swing.JTextField campo_Correo;
    public javax.swing.JTextField campo_Direccion;
    public javax.swing.JTextField campo_RUC;
    public javax.swing.JTextField campo_Telefono;
    public javax.swing.JTextField combo_Cliente;
    public javax.swing.JLabel etiqueta_Ciudad;
    public javax.swing.JLabel etiqueta_Cliente;
    private javax.swing.JLabel etiqueta_Correccion_Correo;
    private javax.swing.JLabel etiqueta_Correccion_RUC;
    public javax.swing.JLabel etiqueta_Correo;
    public javax.swing.JLabel etiqueta_Direccion;
    private javax.swing.JLabel etiqueta_Indicador_Celular;
    private javax.swing.JLabel etiqueta_Indicador_Ciudad;
    private javax.swing.JLabel etiqueta_Indicador_Cliente;
    private javax.swing.JLabel etiqueta_Indicador_Contacto;
    private javax.swing.JLabel etiqueta_Indicador_Correo;
    private javax.swing.JLabel etiqueta_Indicador_Direccion;
    private javax.swing.JLabel etiqueta_Indicador_RUC;
    private javax.swing.JLabel etiqueta_Indicador_Telefono;
    public javax.swing.JLabel etiqueta_Nombre_Usuario;
    public javax.swing.JLabel etiqueta_Persona1;
    public javax.swing.JLabel etiqueta_Persona2;
    public javax.swing.JLabel etiqueta_RUC;
    public javax.swing.JLabel etiqueta_Rol;
    public javax.swing.JLabel etiqueta_Telefono;
    private javax.swing.ButtonGroup grupo_Botones_DNI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JRadioButton radio_Boton_CI;
    private javax.swing.JRadioButton radio_Boton_RUC;
    // End of variables declaration//GEN-END:variables
}
