/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Orden_De_Compra;

import Modelo.Orden_Compra;
import Modelo.Proveedor;
import Modelo.Usuario;
import java.awt.Color;
import java.awt.Font;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author David
 */
public class Panel_Orden_Compra extends javax.swing.JPanel {

    private DefaultTableModel       modelo_Tabla_Datos_Compras;
    private DecimalFormat           formato_Numero = new DecimalFormat("#.00", new DecimalFormatSymbols(Locale.US));
    /**
     * Creates new form Panel_Cotizacion
     */
    public Panel_Orden_Compra() {
        initComponents();
        calendario_Orden_Compra.setDate( new Date() );
        this.modelo_Tabla_Datos_Compras = ( DefaultTableModel )  this.tabla_Productos_Orden_Compra.getModel();
        this.tabla_Productos_Orden_Compra.getTableHeader().setFont( new Font( "Arial", Font.BOLD, 14 ) );
        this.tabla_Productos_Orden_Compra.getTableHeader().setBackground( new Color( 32, 136, 203 ) );
        this.tabla_Productos_Orden_Compra.getTableHeader().setForeground( new Color( 255, 255, 255) );      
        this.etiqueta_Indicador_Proveedor.setVisible( false );
        this.etiqueta_Indicador_RUC.setVisible( false );
        this.etiqueta_Indicador_Direccion.setVisible( false );
        this.etiqueta_Indicador_Telefono.setVisible( false );
        this.etiqueta_Indicador_Correo.setVisible( false );
        this.etiqueta_Indicador_Contacto.setVisible( false );
        this.etiqueta_Indicador_Modalidad.setVisible( false );
        this.etiqueta_Indicador_Estado.setVisible( false );
        this.boton_Modificar_Orden_Compra.setEnabled( false );
        this.boton_Agregar_Fila.setEnabled(false);
        this.boton_Quitar_Fila.setEnabled(false);
        this.boton_Generar_Orden.setEnabled(false);
        this.etiqueta_Indicador_Calendario.setVisible(false);
        this.tabla_Productos_Orden_Compra.getTableHeader().setReorderingAllowed(false) ;
        this.valor_IVA.setValue(12);
        this.valor_IVA.setEnabled(false);
    }
    
    public void Roles(String rol) {
        if (rol.equals("Vendedor")) {
            boolean[] bandera = {true, true, true, true, true, true, false};
            this.habilitar_Rol(bandera);
        }
        
        if (rol.equals("Bodeguero")) {
            boolean[] bandera = {false, false, false, false, false, false, false};
            this.habilitar_Rol(bandera);
        }
        
        if (rol.equals("Contador")) {
            boolean[] bandera = {false, false, false, false, false, false, false};
            this.habilitar_Rol(bandera);
        }
        
        if (rol.equals("Administrador")) {
            boolean[] bandera = {true, true, true, true, true, true, true};
            this.habilitar_Rol(bandera);
        }
    }
    
    public void habilitar_Rol(boolean[] bandera) {
        this.boton_Nueva_Orden_Compra.setVisible(bandera[0]);
        this.boton_Guardar_Orden_Compra.setVisible(bandera[1]);
        this.boton_Modificar_Orden_Compra.setVisible(bandera[2]);
        this.boton_Buscar_Proveedor_Orden.setVisible(bandera[3]);
        this.boton_Agregar_Fila.setVisible(bandera[4]);
        this.boton_Quitar_Fila.setVisible(bandera[5]);
        this.combo_Estado_Orden.setVisible(bandera[6]);
        this.etiqueta_Estado_Combo.setVisible(bandera[6]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        boton_Nueva_Orden_Compra = new javax.swing.JButton();
        boton_Guardar_Orden_Compra = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        boton_Modificar_Orden_Compra = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        boton_Generar_Orden = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        boton_Buscar_Orden_Compra = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        calendario_Orden_Compra = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        campo_Direccion_Orden_Compra = new javax.swing.JTextField();
        campo_Solicitante_Orden_Compra = new javax.swing.JTextField();
        campo_Correo_Orden_Compra = new javax.swing.JTextField();
        campo_Telefono_Orden_Compra = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Productos_Orden_Compra = new javax.swing.JTable();
        campo_Subtotal_Orden_Compra = new javax.swing.JTextField();
        campo_IVA_Orden_Compra = new javax.swing.JTextField();
        campo_Total_Orden_Compra = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        etiqueta_No_Orden_Compra = new javax.swing.JLabel();
        boton_Agregar_Fila = new javax.swing.JButton();
        boton_Quitar_Fila = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        campo_RUC_Orden_Compra = new javax.swing.JTextField();
        etiqueta_Indicador_Proveedor = new javax.swing.JLabel();
        etiqueta_Indicador_Direccion = new javax.swing.JLabel();
        etiqueta_Indicador_Telefono = new javax.swing.JLabel();
        etiqueta_Indicador_Correo = new javax.swing.JLabel();
        etiqueta_Indicador_RUC = new javax.swing.JLabel();
        etiqueta_Indicador_Contacto = new javax.swing.JLabel();
        boton_Buscar_Proveedor_Orden = new javax.swing.JButton();
        etiqueta_Indicador_Modalidad = new javax.swing.JLabel();
        combo_Modalidad_Pago_Orden_Compra = new javax.swing.JComboBox<>();
        combo_Proveedor_Orden_Compra = new javax.swing.JTextField();
        cantidad_Items = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        caja_Observaciones = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        valor_IVA = new javax.swing.JSpinner();
        boton_Cerrar_Sesion = new javax.swing.JButton();
        etiqueta_Estado_Orden = new javax.swing.JLabel();
        combo_Estado_Orden = new javax.swing.JComboBox<>();
        etiqueta_Estado_Combo = new javax.swing.JLabel();
        etiqueta_Indicador_Estado = new javax.swing.JLabel();
        etiqueta_Rol = new javax.swing.JLabel();
        etiqueta_Indicador_Calendario = new javax.swing.JLabel();
        etiqueta_Nombre_Usuario = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.activeCaption);
        setMaximumSize(new java.awt.Dimension(1400, 800));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setPreferredSize(new java.awt.Dimension(1400, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator1);

        boton_Nueva_Orden_Compra.setBackground(new java.awt.Color(255, 255, 255));
        boton_Nueva_Orden_Compra.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Nueva_Orden_Compra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-archivo.png"))); // NOI18N
        boton_Nueva_Orden_Compra.setText("Nuevo");
        boton_Nueva_Orden_Compra.setToolTipText("Nueva cotizacion");
        boton_Nueva_Orden_Compra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Nueva_Orden_Compra.setFocusable(false);
        boton_Nueva_Orden_Compra.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Nueva_Orden_Compra.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Nueva_Orden_Compra.setMinimumSize(new java.awt.Dimension(100, 37));
        boton_Nueva_Orden_Compra.setPreferredSize(new java.awt.Dimension(100, 37));
        boton_Nueva_Orden_Compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Nueva_Orden_CompraActionPerformed(evt);
            }
        });
        jToolBar1.add(boton_Nueva_Orden_Compra);

        boton_Guardar_Orden_Compra.setBackground(new java.awt.Color(255, 255, 255));
        boton_Guardar_Orden_Compra.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Guardar_Orden_Compra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disquete.png"))); // NOI18N
        boton_Guardar_Orden_Compra.setText("Guardar");
        boton_Guardar_Orden_Compra.setToolTipText("Agregar cotizacion");
        boton_Guardar_Orden_Compra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Guardar_Orden_Compra.setFocusable(false);
        boton_Guardar_Orden_Compra.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Guardar_Orden_Compra.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Guardar_Orden_Compra.setMinimumSize(new java.awt.Dimension(60, 37));
        boton_Guardar_Orden_Compra.setPreferredSize(new java.awt.Dimension(60, 37));
        boton_Guardar_Orden_Compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Guardar_Orden_CompraActionPerformed(evt);
            }
        });
        jToolBar1.add(boton_Guardar_Orden_Compra);
        jToolBar1.add(jSeparator2);

        boton_Modificar_Orden_Compra.setBackground(new java.awt.Color(255, 255, 255));
        boton_Modificar_Orden_Compra.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Modificar_Orden_Compra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar-documento.png"))); // NOI18N
        boton_Modificar_Orden_Compra.setText("Modificar");
        boton_Modificar_Orden_Compra.setToolTipText("Editar cotizacion");
        boton_Modificar_Orden_Compra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Modificar_Orden_Compra.setFocusable(false);
        boton_Modificar_Orden_Compra.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Modificar_Orden_Compra.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Modificar_Orden_Compra.setMinimumSize(new java.awt.Dimension(60, 37));
        boton_Modificar_Orden_Compra.setPreferredSize(new java.awt.Dimension(60, 37));
        boton_Modificar_Orden_Compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Modificar_Orden_CompraActionPerformed(evt);
            }
        });
        jToolBar1.add(boton_Modificar_Orden_Compra);
        jToolBar1.add(jSeparator3);

        boton_Generar_Orden.setBackground(new java.awt.Color(255, 255, 255));
        boton_Generar_Orden.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Generar_Orden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportar 1.png"))); // NOI18N
        boton_Generar_Orden.setText("Reporte");
        boton_Generar_Orden.setToolTipText("Generar cotizacion");
        boton_Generar_Orden.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Generar_Orden.setFocusable(false);
        boton_Generar_Orden.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Generar_Orden.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Generar_Orden.setMinimumSize(new java.awt.Dimension(100, 37));
        boton_Generar_Orden.setPreferredSize(new java.awt.Dimension(100, 37));
        jToolBar1.add(boton_Generar_Orden);
        jToolBar1.add(jSeparator4);

        boton_Buscar_Orden_Compra.setBackground(new java.awt.Color(255, 255, 255));
        boton_Buscar_Orden_Compra.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Buscar_Orden_Compra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar-en-carpeta.png"))); // NOI18N
        boton_Buscar_Orden_Compra.setText("Buscar");
        boton_Buscar_Orden_Compra.setToolTipText("Buscr cotizacion");
        boton_Buscar_Orden_Compra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Buscar_Orden_Compra.setFocusable(false);
        boton_Buscar_Orden_Compra.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Buscar_Orden_Compra.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Buscar_Orden_Compra.setMinimumSize(new java.awt.Dimension(100, 37));
        boton_Buscar_Orden_Compra.setPreferredSize(new java.awt.Dimension(100, 37));
        jToolBar1.add(boton_Buscar_Orden_Compra);
        jToolBar1.add(jSeparator6);

        add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 40));

        calendario_Orden_Compra.setBackground(new java.awt.Color(255, 255, 255));
        calendario_Orden_Compra.setDateFormatString("yyyy-MM-dd");
        calendario_Orden_Compra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        add(calendario_Orden_Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 180, 23));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Fecha:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Proveedor:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Direccion:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Telefono:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Solicitante:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Correo:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        campo_Direccion_Orden_Compra.setEditable(false);
        campo_Direccion_Orden_Compra.setBackground(new java.awt.Color(255, 255, 255));
        campo_Direccion_Orden_Compra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Direccion_Orden_Compra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Direccion_Orden_Compra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Direccion_Orden_CompraKeyTyped(evt);
            }
        });
        add(campo_Direccion_Orden_Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 660, 20));

        campo_Solicitante_Orden_Compra.setEditable(false);
        campo_Solicitante_Orden_Compra.setBackground(new java.awt.Color(255, 255, 255));
        campo_Solicitante_Orden_Compra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Solicitante_Orden_Compra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Solicitante_Orden_Compra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Solicitante_Orden_CompraKeyTyped(evt);
            }
        });
        add(campo_Solicitante_Orden_Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 310, 20));

        campo_Correo_Orden_Compra.setEditable(false);
        campo_Correo_Orden_Compra.setBackground(new java.awt.Color(255, 255, 255));
        campo_Correo_Orden_Compra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Correo_Orden_Compra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Correo_Orden_Compra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Correo_Orden_CompraKeyTyped(evt);
            }
        });
        add(campo_Correo_Orden_Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 310, 20));

        campo_Telefono_Orden_Compra.setEditable(false);
        campo_Telefono_Orden_Compra.setBackground(new java.awt.Color(255, 255, 255));
        campo_Telefono_Orden_Compra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Telefono_Orden_Compra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Telefono_Orden_Compra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Telefono_Orden_CompraKeyTyped(evt);
            }
        });
        add(campo_Telefono_Orden_Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 230, 20));

        tabla_Productos_Orden_Compra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabla_Productos_Orden_Compra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cant", "Codigo", "Descripcion", "V. Unitario", "V. Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_Productos_Orden_Compra.setRowHeight(20);
        tabla_Productos_Orden_Compra.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabla_Productos_Orden_CompraPropertyChange(evt);
            }
        });
        tabla_Productos_Orden_Compra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tabla_Productos_Orden_CompraKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_Productos_Orden_Compra);
        if (tabla_Productos_Orden_Compra.getColumnModel().getColumnCount() > 0) {
            tabla_Productos_Orden_Compra.getColumnModel().getColumn(0).setResizable(false);
            tabla_Productos_Orden_Compra.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabla_Productos_Orden_Compra.getColumnModel().getColumn(1).setResizable(false);
            tabla_Productos_Orden_Compra.getColumnModel().getColumn(1).setPreferredWidth(120);
            tabla_Productos_Orden_Compra.getColumnModel().getColumn(2).setResizable(false);
            tabla_Productos_Orden_Compra.getColumnModel().getColumn(2).setPreferredWidth(310);
            tabla_Productos_Orden_Compra.getColumnModel().getColumn(3).setResizable(false);
            tabla_Productos_Orden_Compra.getColumnModel().getColumn(3).setPreferredWidth(50);
            tabla_Productos_Orden_Compra.getColumnModel().getColumn(4).setResizable(false);
            tabla_Productos_Orden_Compra.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 890, 190));

        campo_Subtotal_Orden_Compra.setEditable(false);
        campo_Subtotal_Orden_Compra.setBackground(new java.awt.Color(255, 255, 255));
        campo_Subtotal_Orden_Compra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Subtotal_Orden_Compra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(campo_Subtotal_Orden_Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 660, 80, -1));

        campo_IVA_Orden_Compra.setEditable(false);
        campo_IVA_Orden_Compra.setBackground(new java.awt.Color(255, 255, 255));
        campo_IVA_Orden_Compra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_IVA_Orden_Compra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(campo_IVA_Orden_Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 690, 80, 20));

        campo_Total_Orden_Compra.setEditable(false);
        campo_Total_Orden_Compra.setBackground(new java.awt.Color(255, 255, 255));
        campo_Total_Orden_Compra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Total_Orden_Compra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(campo_Total_Orden_Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 720, 80, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Subtotal:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 660, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("IVA:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 690, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Total:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 720, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Tipo de pago:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("Numero de O/C:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 72, -1, 20));

        etiqueta_No_Orden_Compra.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        add(etiqueta_No_Orden_Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 210, 23));

        boton_Agregar_Fila.setBackground(new java.awt.Color(255, 255, 255));
        boton_Agregar_Fila.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Agregar_Fila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mas (1).png"))); // NOI18N
        boton_Agregar_Fila.setText("Agregar producto");
        boton_Agregar_Fila.setToolTipText("Agregar");
        boton_Agregar_Fila.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Agregar_Fila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Agregar_FilaActionPerformed(evt);
            }
        });
        add(boton_Agregar_Fila, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 450, 140, 32));

        boton_Quitar_Fila.setBackground(new java.awt.Color(255, 255, 255));
        boton_Quitar_Fila.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Quitar_Fila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menos.png"))); // NOI18N
        boton_Quitar_Fila.setText("Quitar producto");
        boton_Quitar_Fila.setToolTipText("Quitar producto");
        boton_Quitar_Fila.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Quitar_Fila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Quitar_FilaActionPerformed(evt);
            }
        });
        add(boton_Quitar_Fila, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 500, 140, 32));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("RUC:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, -1));

        campo_RUC_Orden_Compra.setEditable(false);
        campo_RUC_Orden_Compra.setBackground(new java.awt.Color(255, 255, 255));
        campo_RUC_Orden_Compra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_RUC_Orden_Compra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_RUC_Orden_Compra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_RUC_Orden_CompraKeyTyped(evt);
            }
        });
        add(campo_RUC_Orden_Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 180, 20));

        etiqueta_Indicador_Proveedor.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Proveedor.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Proveedor.setText("*");
        add(etiqueta_Indicador_Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, -1, -1));

        etiqueta_Indicador_Direccion.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Direccion.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Direccion.setText("*");
        add(etiqueta_Indicador_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, -1, -1));

        etiqueta_Indicador_Telefono.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Telefono.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Telefono.setText("*");
        add(etiqueta_Indicador_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        etiqueta_Indicador_Correo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Correo.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Correo.setText("*");
        add(etiqueta_Indicador_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, 20, -1));

        etiqueta_Indicador_RUC.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_RUC.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_RUC.setText("*");
        add(etiqueta_Indicador_RUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        etiqueta_Indicador_Contacto.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Contacto.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Contacto.setText("*");
        add(etiqueta_Indicador_Contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, -1));

        boton_Buscar_Proveedor_Orden.setBackground(new java.awt.Color(255, 255, 255));
        boton_Buscar_Proveedor_Orden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        boton_Buscar_Proveedor_Orden.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(boton_Buscar_Proveedor_Orden, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 155, 50, -1));

        etiqueta_Indicador_Modalidad.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Modalidad.setForeground(new java.awt.Color(198, 0, 0));
        etiqueta_Indicador_Modalidad.setText("*");
        add(etiqueta_Indicador_Modalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, -1, -1));

        combo_Modalidad_Pago_Orden_Compra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combo_Modalidad_Pago_Orden_Compra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar......", "Credito", "Contado", "Anulado" }));
        add(combo_Modalidad_Pago_Orden_Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 200, -1));

        combo_Proveedor_Orden_Compra.setEditable(false);
        combo_Proveedor_Orden_Compra.setBackground(new java.awt.Color(255, 255, 255));
        combo_Proveedor_Orden_Compra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combo_Proveedor_Orden_Compra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(combo_Proveedor_Orden_Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 320, 20));

        cantidad_Items.setEditable(false);
        cantidad_Items.setBackground(new java.awt.Color(255, 255, 255));
        cantidad_Items.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cantidad_Items.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(cantidad_Items, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 660, 110, 22));

        caja_Observaciones.setColumns(20);
        caja_Observaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        caja_Observaciones.setRows(5);
        jScrollPane3.setViewportView(caja_Observaciones);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 660, 330, 90));

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Total", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 1110, 130));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Items");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 660, -1, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel20.setText("IVA %:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 325, -1, -1));

        valor_IVA.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        valor_IVA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                valor_IVAStateChanged(evt);
            }
        });
        valor_IVA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valor_IVAKeyTyped(evt);
            }
        });
        add(valor_IVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 110, 23));

        boton_Cerrar_Sesion.setBackground(new java.awt.Color(255, 255, 255));
        boton_Cerrar_Sesion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Cerrar_Sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit-32.png"))); // NOI18N
        boton_Cerrar_Sesion.setText("Cerrar");
        boton_Cerrar_Sesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(boton_Cerrar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 120, 40));

        etiqueta_Estado_Orden.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        etiqueta_Estado_Orden.setForeground(new java.awt.Color(51, 153, 0));
        add(etiqueta_Estado_Orden, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 58, 460, 40));

        combo_Estado_Orden.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combo_Estado_Orden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar.....", "Aprobado", "No Aprobado" }));
        add(combo_Estado_Orden, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 160, -1));

        etiqueta_Estado_Combo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Estado_Combo.setText("Estado:");
        add(etiqueta_Estado_Combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        etiqueta_Indicador_Estado.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Estado.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Estado.setText("*");
        add(etiqueta_Indicador_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        etiqueta_Rol.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiqueta_Rol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(etiqueta_Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(1134, 20, 147, 20));

        etiqueta_Indicador_Calendario.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Calendario.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Calendario.setText("*");
        add(etiqueta_Indicador_Calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 20, -1));

        etiqueta_Nombre_Usuario.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiqueta_Nombre_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        etiqueta_Nombre_Usuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        etiqueta_Nombre_Usuario.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(etiqueta_Nombre_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 180, 40));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo blanco.png"))); // NOI18N
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 180, 40));

        jLabel14.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1110, 60));

        jLabel19.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Informacion proveedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 1110, 250));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 1110, 250));
    }// </editor-fold>//GEN-END:initComponents

    private void boton_Quitar_FilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Quitar_FilaActionPerformed
        try{
            modelo_Tabla_Datos_Compras.removeRow( this.tabla_Productos_Orden_Compra.getSelectedRow() );
            this.cantidad_Items.setText(String.valueOf(this.tabla_Productos_Orden_Compra.getRowCount()));
            calculo_Valores();
        }catch( Exception e1 ){}
    }//GEN-LAST:event_boton_Quitar_FilaActionPerformed

    private void campo_Direccion_Orden_CompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Direccion_Orden_CompraKeyTyped

    }//GEN-LAST:event_campo_Direccion_Orden_CompraKeyTyped

    private void campo_RUC_Orden_CompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_RUC_Orden_CompraKeyTyped
        char c = evt.getKeyChar();
        if( c < '0'  || c > '9' || this.campo_RUC_Orden_Compra.getText().length() >= 13 ) evt.consume();
    }//GEN-LAST:event_campo_RUC_Orden_CompraKeyTyped

    private void campo_Telefono_Orden_CompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Telefono_Orden_CompraKeyTyped

    }//GEN-LAST:event_campo_Telefono_Orden_CompraKeyTyped

    private void campo_Solicitante_Orden_CompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Solicitante_Orden_CompraKeyTyped

    }//GEN-LAST:event_campo_Solicitante_Orden_CompraKeyTyped

    private void campo_Correo_Orden_CompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Correo_Orden_CompraKeyTyped

    }//GEN-LAST:event_campo_Correo_Orden_CompraKeyTyped

    private void tabla_Productos_Orden_CompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_Productos_Orden_CompraKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla_Productos_Orden_CompraKeyTyped

    private void boton_Nueva_Orden_CompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Nueva_Orden_CompraActionPerformed
        
    }//GEN-LAST:event_boton_Nueva_Orden_CompraActionPerformed

    private void boton_Agregar_FilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Agregar_FilaActionPerformed
        this.cantidad_Items.setText(String.valueOf(this.tabla_Productos_Orden_Compra.getRowCount()));
    }//GEN-LAST:event_boton_Agregar_FilaActionPerformed

    private void tabla_Productos_Orden_CompraPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabla_Productos_Orden_CompraPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla_Productos_Orden_CompraPropertyChange

    private void boton_Modificar_Orden_CompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Modificar_Orden_CompraActionPerformed
        this.cantidad_Items.setText(String.valueOf(this.tabla_Productos_Orden_Compra.getRowCount()));
    }//GEN-LAST:event_boton_Modificar_Orden_CompraActionPerformed

    private void boton_Guardar_Orden_CompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Guardar_Orden_CompraActionPerformed
        this.cantidad_Items.setText(String.valueOf(this.tabla_Productos_Orden_Compra.getRowCount()));
    }//GEN-LAST:event_boton_Guardar_Orden_CompraActionPerformed

    private void valor_IVAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_valor_IVAStateChanged

        if((Integer)this.valor_IVA.getValue() < 1){
            this.valor_IVA.setValue(1);
        }else if((Integer)this.valor_IVA.getValue() > 25){
            this.valor_IVA.setValue(25);
        }else{
            calculo_Valores();
        }
    }//GEN-LAST:event_valor_IVAStateChanged

    private void valor_IVAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valor_IVAKeyTyped

    }//GEN-LAST:event_valor_IVAKeyTyped
 
    public void calculo_Valores() {
        try {
            double valor_Subtotal = 0;
            for (int i = 0; i < modelo_Tabla_Datos_Compras.getRowCount(); i++) {
                valor_Subtotal = valor_Subtotal + (double) modelo_Tabla_Datos_Compras.getValueAt(i, 4);
            }
            this.campo_Subtotal_Orden_Compra.setText(this.formato_Numero.format(valor_Subtotal));
            this.campo_IVA_Orden_Compra.setText(this.formato_Numero.format(valor_Subtotal * (Integer)this.valor_IVA.getValue()/100));
            this.campo_Total_Orden_Compra.setText(this.formato_Numero.format(Double.valueOf(this.campo_IVA_Orden_Compra.getText()) + valor_Subtotal));
        } catch (Exception e) {
        }
    }
    
    public boolean etiquetas( ){ 
        boolean bandera=true;
        
        if( this.combo_Proveedor_Orden_Compra.getText().isEmpty() ){ 
            this.etiqueta_Indicador_Proveedor.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Proveedor.setVisible( false );
        }
        
        if( this.campo_RUC_Orden_Compra.getText().matches( "[0-9][0-9]{12}" ) ){
            this.etiqueta_Indicador_RUC.setVisible( false );
        }else if(this.campo_RUC_Orden_Compra.getText().matches( "[0-9][0-9]{9}" ) ){
            this.etiqueta_Indicador_RUC.setVisible( false );
        }
        else{
            this.etiqueta_Indicador_RUC.setVisible( true );
            bandera = false;
        }
        
        if (this.calendario_Orden_Compra.getDate() == null) {
            this.etiqueta_Indicador_Calendario.setVisible(bandera);
            bandera = false;
        }else{
            this.etiqueta_Indicador_Calendario.setVisible(false);
        }
            
        if( this.campo_Direccion_Orden_Compra.getText().isEmpty() ){ 
            this.etiqueta_Indicador_Direccion.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Direccion.setVisible( false );
        }
            
        if( this.campo_Telefono_Orden_Compra.getText().matches( "[0][1-9][0-9]{7}" ) ){
            this.etiqueta_Indicador_Telefono.setVisible( false );
        }else{
            this.etiqueta_Indicador_Telefono.setVisible( true );
            bandera = false;
        }  
        
        if( this.campo_Correo_Orden_Compra.getText().matches( "[a-zA-Z_\\d]+@[a-zA-Z]+(\\.[a-zA-Z]*)+" )){  
            this.etiqueta_Indicador_Correo.setVisible( false );
        }else{
            this.etiqueta_Indicador_Correo.setVisible( true );
            bandera = false;
        }
            
        if( this.campo_Solicitante_Orden_Compra.getText().isEmpty() ){
            this.etiqueta_Indicador_Contacto.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Contacto.setVisible( false );
        }
        
        if( this.combo_Modalidad_Pago_Orden_Compra.getSelectedItem().equals( "Seleccionar......" ) ){
            this.etiqueta_Indicador_Modalidad.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Modalidad.setVisible( false );
        }
        
        if (this.combo_Estado_Orden.isVisible()) {
            if (this.combo_Estado_Orden.getSelectedItem().equals("Seleccionar.....")) {
                this.etiqueta_Indicador_Estado.setVisible(true);
                bandera = false;
            } else {
                this.etiqueta_Indicador_Estado.setVisible(false);
            }
        }
        
        return bandera;
    }
    
    public String[] evaluar_Tabla(){
        DefaultTableModel modelo_Tabla_Cotizacion = (DefaultTableModel) this.tabla_Productos_Orden_Compra.getModel();
        String[] valores = new String[6];

        for (int i = 0; i < modelo_Tabla_Cotizacion.getRowCount(); i++) {
            valores[0] = modelo_Tabla_Cotizacion.getValueAt(i, 0) + ";" + valores[0];
            valores[1] = modelo_Tabla_Cotizacion.getValueAt(i, 1) + ";" + valores[1];
            valores[2] = modelo_Tabla_Cotizacion.getValueAt(i, 2) + ";" + valores[2];
            valores[3] = modelo_Tabla_Cotizacion.getValueAt(i, 3) + ";" + valores[3];
            valores[4] = modelo_Tabla_Cotizacion.getValueAt(i, 4) + ";" + valores[4];
        }
        return valores;
    }
    
    public String calendario_Fecha() {
        Date fecha;
        fecha = (Date) this.calendario_Orden_Compra.getDate();
        return new SimpleDateFormat("yyyy-MM-dd").format(fecha);
    }
    
    public void limpiar_Valores(){
        this.campo_Subtotal_Orden_Compra.setText( "" );
        this.campo_Solicitante_Orden_Compra.setText( "" );
        this.campo_IVA_Orden_Compra.setText( "" );
        this.campo_Total_Orden_Compra.setText( "" );
        this.campo_Solicitante_Orden_Compra.setText( "" );
        this.combo_Modalidad_Pago_Orden_Compra.setSelectedItem( "" );
        this.combo_Proveedor_Orden_Compra.setText("" );
        this.combo_Modalidad_Pago_Orden_Compra.setSelectedItem( "Seleccionar......" );
        this.caja_Observaciones.setText("");
        this.etiqueta_Estado_Orden.setText("");
        this.combo_Estado_Orden.setSelectedItem("Seleccionar.....");
        this.valor_IVA.setValue(12);
    }
    
    public void limpiar_Tabla(){
        DefaultTableModel modelo_Tabla_Cotizacion = ( DefaultTableModel ) this.tabla_Productos_Orden_Compra.getModel();
        modelo_Tabla_Cotizacion.setRowCount( 0 );
    }
    
    public void botones(boolean bandera1, boolean bandera2, boolean bandera3, boolean bandera4, boolean bandera5, boolean bandera6, boolean bandera7) {
        this.boton_Guardar_Orden_Compra.setEnabled(bandera1);
        this.boton_Buscar_Proveedor_Orden.setEnabled(bandera1);
        this.boton_Nueva_Orden_Compra.setEnabled(bandera2);
        this.boton_Modificar_Orden_Compra.setEnabled(bandera3);
        this.boton_Generar_Orden.setEnabled(bandera4);
        this.combo_Modalidad_Pago_Orden_Compra.setEnabled(bandera5);
        this.boton_Agregar_Fila.setEnabled(bandera6);
        this.boton_Quitar_Fila.setEnabled(bandera6);
        this.combo_Estado_Orden.setEnabled(bandera7);
        this.valor_IVA.setEnabled(bandera6);
    }
    
    public void valores_Tabla_Orden(Orden_Compra lista_Orden, Proveedor proveedor) {
        DefaultTableModel modelo_Tabla_Orden = (DefaultTableModel) this.tabla_Productos_Orden_Compra.getModel();
        modelo_Tabla_Orden.setRowCount(0);

        String[] cantidad = lista_Orden.getCantidad().split(";");
        String[] codigo = lista_Orden.getCodigo().split(";");
        String[] descripcion = lista_Orden.getDescripcion().split(";");
        String[] v_Unitario = lista_Orden.getV_Unitario().split(";");
        String[] v_Total = lista_Orden.getV_Total().split(";");

        for (int i = 0; i < codigo.length - 1; i++) {
            Object[] valores_Tabla = {cantidad[i], codigo[i], descripcion[i], Double.parseDouble(v_Unitario[i]), Double.parseDouble(v_Total[i])};
            modelo_Tabla_Orden.addRow(valores_Tabla);
        }
        this.cantidad_Items.setText(String.valueOf(codigo.length - 1));
        this.valores_Proveedores(proveedor.getProveedor(), proveedor.getDireccion(), proveedor.getTelefono(), proveedor.getCorreo(), proveedor.getRUC(), lista_Orden.getSolicitante(), "");
        this.valores_Orden_Compra(lista_Orden.getProveedor(), lista_Orden.getV_Subtotal(), lista_Orden.getIVA(), lista_Orden.getValor_Total(), lista_Orden.getTipo_Pago(), lista_Orden.getNo_Orden(), lista_Orden.getEstado());
    }

    public void valores_Orden_Compra(String proveedor, double subtotal, double IVA, double valor_Total, String tipo_Pago, String no_Orden, String estado) {
        this.campo_Subtotal_Orden_Compra.setText(String.valueOf(subtotal));
        this.campo_IVA_Orden_Compra.setText(String.valueOf(IVA));
        this.campo_Total_Orden_Compra.setText(String.valueOf(valor_Total));
        this.combo_Modalidad_Pago_Orden_Compra.setSelectedItem(tipo_Pago);
        this.etiqueta_No_Orden_Compra.setText(no_Orden);
        this.color_Etiqueta_Estado(estado);
        this.valor_IVA.setValue((int)((IVA/subtotal)*100));
    }
    
    public void valores_Proveedores(String proveedor, String direccion, String telefono, String correo, String RUC, String nombre, String apellido) {
        this.combo_Proveedor_Orden_Compra.setText(proveedor);
        this.campo_Direccion_Orden_Compra.setText(direccion);
        this.campo_Telefono_Orden_Compra.setText(telefono);
        this.campo_Correo_Orden_Compra.setText(correo);
        this.campo_RUC_Orden_Compra.setText(RUC);
        this.campo_Solicitante_Orden_Compra.setText(nombre + " " + apellido);
    }
    
    public void limpiar_Etiquetas() {
        this.etiqueta_Indicador_Proveedor.setVisible(false);
        this.etiqueta_Indicador_RUC.setVisible(false);
        this.etiqueta_Indicador_RUC.setVisible(false);
        this.etiqueta_Indicador_Direccion.setVisible(false);
        this.etiqueta_Indicador_Telefono.setVisible(false);
        this.etiqueta_Indicador_Correo.setVisible(false);
        this.etiqueta_Indicador_Contacto.setVisible(false);
        this.etiqueta_Indicador_Modalidad.setVisible(false);
    }
    
    public void color_Etiqueta_Estado(String estado){
        this.etiqueta_Estado_Orden.setText(estado.toUpperCase());
        
        if(estado.equals("En revision")){
            this.etiqueta_Estado_Orden.setForeground(Color.blue);
        }else if(estado.equals("No Aprobado")){
            this.etiqueta_Estado_Orden.setForeground(Color.RED);
        }else if(estado.equals("Aprobado")){
            this.etiqueta_Estado_Orden.setForeground(Color.GREEN);
        }else if(estado.equals("Anulado")){
            this.etiqueta_Estado_Orden.setForeground(Color.BLACK);
        }
    }
    
    public void set_Usuario(Usuario usuario, String rol){
        this.etiqueta_Nombre_Usuario.setText(usuario.getNombre() + " " + usuario.getApellido());
        this.etiqueta_Rol.setText(rol);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton boton_Agregar_Fila;
    public javax.swing.JButton boton_Buscar_Orden_Compra;
    public javax.swing.JButton boton_Buscar_Proveedor_Orden;
    public javax.swing.JButton boton_Cerrar_Sesion;
    public javax.swing.JButton boton_Generar_Orden;
    public javax.swing.JButton boton_Guardar_Orden_Compra;
    public javax.swing.JButton boton_Modificar_Orden_Compra;
    public javax.swing.JButton boton_Nueva_Orden_Compra;
    public javax.swing.JButton boton_Quitar_Fila;
    public javax.swing.JTextArea caja_Observaciones;
    public com.toedter.calendar.JDateChooser calendario_Orden_Compra;
    public javax.swing.JTextField campo_Correo_Orden_Compra;
    public javax.swing.JTextField campo_Direccion_Orden_Compra;
    public javax.swing.JTextField campo_IVA_Orden_Compra;
    public javax.swing.JTextField campo_RUC_Orden_Compra;
    public javax.swing.JTextField campo_Solicitante_Orden_Compra;
    public javax.swing.JTextField campo_Subtotal_Orden_Compra;
    public javax.swing.JTextField campo_Telefono_Orden_Compra;
    public javax.swing.JTextField campo_Total_Orden_Compra;
    private javax.swing.JTextField cantidad_Items;
    public javax.swing.JComboBox<String> combo_Estado_Orden;
    public javax.swing.JComboBox<String> combo_Modalidad_Pago_Orden_Compra;
    public javax.swing.JTextField combo_Proveedor_Orden_Compra;
    private javax.swing.JLabel etiqueta_Estado_Combo;
    public javax.swing.JLabel etiqueta_Estado_Orden;
    private javax.swing.JLabel etiqueta_Indicador_Calendario;
    private javax.swing.JLabel etiqueta_Indicador_Contacto;
    private javax.swing.JLabel etiqueta_Indicador_Correo;
    private javax.swing.JLabel etiqueta_Indicador_Direccion;
    public javax.swing.JLabel etiqueta_Indicador_Estado;
    private javax.swing.JLabel etiqueta_Indicador_Modalidad;
    private javax.swing.JLabel etiqueta_Indicador_Proveedor;
    private javax.swing.JLabel etiqueta_Indicador_RUC;
    private javax.swing.JLabel etiqueta_Indicador_Telefono;
    public javax.swing.JLabel etiqueta_No_Orden_Compra;
    public javax.swing.JLabel etiqueta_Nombre_Usuario;
    public javax.swing.JLabel etiqueta_Rol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JTable tabla_Productos_Orden_Compra;
    public javax.swing.JSpinner valor_IVA;
    // End of variables declaration//GEN-END:variables

}
