/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Cotizacion;

import Modelo.Cliente;
import Modelo.Cotizacion;
import Modelo.Usuario;
import java.awt.Color;
import java.awt.Font;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author David
 */
public class Panel_Cotizacion extends javax.swing.JPanel {
    private DefaultTableModel       modelo_Tabla_Datos_Cotizacion;
    private DecimalFormat           formato_Numero = new DecimalFormat("#.00", new DecimalFormatSymbols(Locale.US));
    /**
     * Creates new form Panel_Cotizacion
     */
    public Panel_Cotizacion() {
        initComponents();
        this.calendario_Cotizacion.setDate(new Date());
        this.modelo_Tabla_Datos_Cotizacion = (DefaultTableModel) this.tabla_Productos_Cotizacion.getModel();
        this.tabla_Productos_Cotizacion.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
        this.tabla_Productos_Cotizacion.getTableHeader().setBackground(new Color(32, 136, 203));
        this.tabla_Productos_Cotizacion.getTableHeader().setForeground(new Color(255, 255, 255));
        this.etiqueta_Indicador_Cliente.setVisible(false);
        this.etiqueta_Indicador_Ciudad.setVisible(false);
        this.etiqueta_Indicador_RUC.setVisible(false);
        this.etiqueta_Indicador_Direccion.setVisible(false);
        this.etiqueta_Indicador_Telefono.setVisible(false);
        this.etiqueta_Indicador_Correo.setVisible(false);
        this.etiqueta_Indicador_Contacto.setVisible(false);
        this.etiqueta_Indicador_Modalidad.setVisible(false);
        this.boton_Modificar_Cotizacion.setEnabled(false);
        this.boton_Generar_Cotizacion.setEnabled(false);
        this.boton_Agregar_Fila.setEnabled(false);
        this.boton_Quitar_Fila.setEnabled(false);
        this.etiqueta_Indicador_Calendario.setVisible(false);
        this.tabla_Productos_Cotizacion.getTableHeader().setReorderingAllowed(false) ;
        this.valor_IVA.setValue(12);
        this.valor_IVA.setEnabled(false);
    }
    
    public void Roles(String rol) {
        if (rol.equals("Vendedor")) {
            boolean[] bandera = {true, true, true, true, true, true, true};
            this.habilitar_Rol(bandera);
        }

        if (rol.equals("Bodeguero")) {
            boolean[] bandera = {false, false, false, false, false, false, false};
            this.habilitar_Rol(bandera);
        }

        if (rol.equals("Contador")) {
            boolean[] bandera = {true, false, false, false, false, false, false};
            this.habilitar_Rol(bandera);
        }

        if (rol.equals("Administrador")) {
            boolean[] bandera = {true, false, false, false, false, false, false};
            this.habilitar_Rol(bandera);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        boton_Nueva_Cotizacion = new javax.swing.JButton();
        boton_Guardar_Cotizacion = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        boton_Modificar_Cotizacion = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        boton_Generar_Cotizacion = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        boton_Buscar_Cotizacion = new javax.swing.JButton();
        calendario_Cotizacion = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        campo_Direccion_Cotizacion = new javax.swing.JTextField();
        campo_Contacto_Cotizacion = new javax.swing.JTextField();
        campo_Correo_Cotizacion = new javax.swing.JTextField();
        campo_Telefono_Cotizacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Productos_Cotizacion = new javax.swing.JTable();
        campo_Subtotal_Cotizacion = new javax.swing.JTextField();
        campo_IVA_Cotizacion = new javax.swing.JTextField();
        campo_Total_Cotizacion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        campo_Modalidad_Cotizacion = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        etiqueta_No_Cotizacion = new javax.swing.JLabel();
        boton_Agregar_Fila = new javax.swing.JButton();
        boton_Quitar_Fila = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        campo_RUC_Cotizacion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        campo_Ciudad_Cotizacion = new javax.swing.JTextField();
        etiqueta_Indicador_Cliente = new javax.swing.JLabel();
        etiqueta_Indicador_Direccion = new javax.swing.JLabel();
        etiqueta_Indicador_Telefono = new javax.swing.JLabel();
        etiqueta_Indicador_Ciudad = new javax.swing.JLabel();
        etiqueta_Indicador_Correo = new javax.swing.JLabel();
        etiqueta_Indicador_RUC = new javax.swing.JLabel();
        etiqueta_Indicador_Contacto = new javax.swing.JLabel();
        etiqueta_Indicador_Modalidad = new javax.swing.JLabel();
        boton_Agregar_Cliente = new javax.swing.JButton();
        combo_Cliente_Cotizacion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        campo_Emisor_Cotizacion = new javax.swing.JTextField();
        boton_Cerrar_Sesion = new javax.swing.JButton();
        campo_Codigo_Cliente = new javax.swing.JTextField();
        etiqueta_Rol = new javax.swing.JLabel();
        etiqueta_Nombre_Usuario = new javax.swing.JLabel();
        etiqueta_Indicador_Calendario = new javax.swing.JLabel();
        valor_IVA = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.activeCaption);
        setMaximumSize(new java.awt.Dimension(1400, 800));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setPreferredSize(new java.awt.Dimension(1400, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator1);

        boton_Nueva_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        boton_Nueva_Cotizacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Nueva_Cotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-archivo.png"))); // NOI18N
        boton_Nueva_Cotizacion.setText("Nuevo");
        boton_Nueva_Cotizacion.setToolTipText("Nueva cotizacion");
        boton_Nueva_Cotizacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Nueva_Cotizacion.setFocusable(false);
        boton_Nueva_Cotizacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Nueva_Cotizacion.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Nueva_Cotizacion.setMinimumSize(new java.awt.Dimension(100, 37));
        boton_Nueva_Cotizacion.setPreferredSize(new java.awt.Dimension(100, 37));
        boton_Nueva_Cotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Nueva_CotizacionActionPerformed(evt);
            }
        });
        jToolBar1.add(boton_Nueva_Cotizacion);

        boton_Guardar_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        boton_Guardar_Cotizacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Guardar_Cotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disquete.png"))); // NOI18N
        boton_Guardar_Cotizacion.setText("Guardar");
        boton_Guardar_Cotizacion.setToolTipText("Agregar cotizacion");
        boton_Guardar_Cotizacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Guardar_Cotizacion.setFocusable(false);
        boton_Guardar_Cotizacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Guardar_Cotizacion.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Guardar_Cotizacion.setMinimumSize(new java.awt.Dimension(60, 37));
        boton_Guardar_Cotizacion.setPreferredSize(new java.awt.Dimension(60, 37));
        jToolBar1.add(boton_Guardar_Cotizacion);
        jToolBar1.add(jSeparator2);

        boton_Modificar_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        boton_Modificar_Cotizacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Modificar_Cotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar-documento.png"))); // NOI18N
        boton_Modificar_Cotizacion.setText("Modificar");
        boton_Modificar_Cotizacion.setToolTipText("Modificar cotizacion");
        boton_Modificar_Cotizacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Modificar_Cotizacion.setFocusable(false);
        boton_Modificar_Cotizacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Modificar_Cotizacion.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Modificar_Cotizacion.setMinimumSize(new java.awt.Dimension(100, 37));
        boton_Modificar_Cotizacion.setPreferredSize(new java.awt.Dimension(60, 37));
        jToolBar1.add(boton_Modificar_Cotizacion);
        jToolBar1.add(jSeparator3);

        boton_Generar_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        boton_Generar_Cotizacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Generar_Cotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportar 1.png"))); // NOI18N
        boton_Generar_Cotizacion.setText("Cotizacion");
        boton_Generar_Cotizacion.setToolTipText("Generar cotizacion");
        boton_Generar_Cotizacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Generar_Cotizacion.setFocusable(false);
        boton_Generar_Cotizacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Generar_Cotizacion.setMaximumSize(new java.awt.Dimension(110, 37));
        boton_Generar_Cotizacion.setMinimumSize(new java.awt.Dimension(110, 37));
        boton_Generar_Cotizacion.setPreferredSize(new java.awt.Dimension(110, 37));
        jToolBar1.add(boton_Generar_Cotizacion);
        jToolBar1.add(jSeparator5);

        boton_Buscar_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        boton_Buscar_Cotizacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Buscar_Cotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar-en-carpeta.png"))); // NOI18N
        boton_Buscar_Cotizacion.setText("Buscar");
        boton_Buscar_Cotizacion.setToolTipText("Buscar cotizacion");
        boton_Buscar_Cotizacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Buscar_Cotizacion.setFocusable(false);
        boton_Buscar_Cotizacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Buscar_Cotizacion.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Buscar_Cotizacion.setMinimumSize(new java.awt.Dimension(100, 37));
        boton_Buscar_Cotizacion.setPreferredSize(new java.awt.Dimension(100, 37));
        jToolBar1.add(boton_Buscar_Cotizacion);

        add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 40));

        calendario_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        calendario_Cotizacion.setDateFormatString("yyyy-MM-dd");
        calendario_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        add(calendario_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 160, 22));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel3.setText("Fecha:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel5.setText("Cliente:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Direccion:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Telefono:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 195, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Solicitante:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Correo:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));

        campo_Direccion_Cotizacion.setEditable(false);
        campo_Direccion_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        campo_Direccion_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Direccion_Cotizacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Direccion_Cotizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Direccion_CotizacionKeyTyped(evt);
            }
        });
        add(campo_Direccion_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 310, 22));

        campo_Contacto_Cotizacion.setEditable(false);
        campo_Contacto_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        campo_Contacto_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Contacto_Cotizacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Contacto_Cotizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Contacto_CotizacionKeyTyped(evt);
            }
        });
        add(campo_Contacto_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 280, 22));

        campo_Correo_Cotizacion.setEditable(false);
        campo_Correo_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        campo_Correo_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Correo_Cotizacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Correo_Cotizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Correo_CotizacionKeyTyped(evt);
            }
        });
        add(campo_Correo_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 300, 22));

        campo_Telefono_Cotizacion.setEditable(false);
        campo_Telefono_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        campo_Telefono_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Telefono_Cotizacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Telefono_Cotizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Telefono_CotizacionKeyTyped(evt);
            }
        });
        add(campo_Telefono_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 195, 150, 22));

        tabla_Productos_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabla_Productos_Cotizacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cant", "Codigo", "Descripcion", "V. Unitario", "V. Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_Productos_Cotizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tabla_Productos_CotizacionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_Productos_Cotizacion);
        if (tabla_Productos_Cotizacion.getColumnModel().getColumnCount() > 0) {
            tabla_Productos_Cotizacion.getColumnModel().getColumn(0).setResizable(false);
            tabla_Productos_Cotizacion.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabla_Productos_Cotizacion.getColumnModel().getColumn(1).setResizable(false);
            tabla_Productos_Cotizacion.getColumnModel().getColumn(1).setPreferredWidth(120);
            tabla_Productos_Cotizacion.getColumnModel().getColumn(2).setResizable(false);
            tabla_Productos_Cotizacion.getColumnModel().getColumn(2).setPreferredWidth(310);
            tabla_Productos_Cotizacion.getColumnModel().getColumn(3).setResizable(false);
            tabla_Productos_Cotizacion.getColumnModel().getColumn(3).setPreferredWidth(50);
            tabla_Productos_Cotizacion.getColumnModel().getColumn(4).setResizable(false);
            tabla_Productos_Cotizacion.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 830, 240));

        campo_Subtotal_Cotizacion.setEditable(false);
        campo_Subtotal_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        campo_Subtotal_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Subtotal_Cotizacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(campo_Subtotal_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 630, 100, 23));

        campo_IVA_Cotizacion.setEditable(false);
        campo_IVA_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        campo_IVA_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_IVA_Cotizacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(campo_IVA_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 660, 100, 23));

        campo_Total_Cotizacion.setEditable(false);
        campo_Total_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        campo_Total_Cotizacion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        campo_Total_Cotizacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(campo_Total_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 690, 100, 23));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Subtotal:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 630, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("IVA:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 660, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Total:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 690, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Modalidad de pago:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, -1, -1));

        campo_Modalidad_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Modalidad_Cotizacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Modalidad_Cotizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Modalidad_CotizacionKeyTyped(evt);
            }
        });
        add(campo_Modalidad_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 630, 200, 20));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel15.setText("No. Cotizacion:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        etiqueta_No_Cotizacion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        add(etiqueta_No_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 170, 21));

        boton_Agregar_Fila.setBackground(new java.awt.Color(255, 255, 255));
        boton_Agregar_Fila.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Agregar_Fila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mas (1).png"))); // NOI18N
        boton_Agregar_Fila.setText("Agregar producto");
        boton_Agregar_Fila.setToolTipText("Agregar");
        boton_Agregar_Fila.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(boton_Agregar_Fila, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 420, 140, -1));

        boton_Quitar_Fila.setBackground(new java.awt.Color(255, 255, 255));
        boton_Quitar_Fila.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Quitar_Fila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menos.png"))); // NOI18N
        boton_Quitar_Fila.setText("Quitar producto");
        boton_Quitar_Fila.setToolTipText("Quitar");
        boton_Quitar_Fila.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Quitar_Fila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Quitar_FilaActionPerformed(evt);
            }
        });
        add(boton_Quitar_Fila, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 470, 140, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel16.setText("RUC:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 162, -1, -1));

        campo_RUC_Cotizacion.setEditable(false);
        campo_RUC_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        campo_RUC_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_RUC_Cotizacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_RUC_Cotizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_RUC_CotizacionKeyTyped(evt);
            }
        });
        add(campo_RUC_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 230, 22));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel18.setText("Ciudad:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, -1, -1));

        campo_Ciudad_Cotizacion.setEditable(false);
        campo_Ciudad_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        campo_Ciudad_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Ciudad_Cotizacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Ciudad_Cotizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Ciudad_CotizacionKeyTyped(evt);
            }
        });
        add(campo_Ciudad_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 230, 22));

        etiqueta_Indicador_Cliente.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Cliente.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Cliente.setText("*");
        add(etiqueta_Indicador_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        etiqueta_Indicador_Direccion.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Direccion.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Direccion.setText("*");
        add(etiqueta_Indicador_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        etiqueta_Indicador_Telefono.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Telefono.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Telefono.setText("*");
        add(etiqueta_Indicador_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 195, -1, -1));

        etiqueta_Indicador_Ciudad.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Ciudad.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Ciudad.setText("*");
        add(etiqueta_Indicador_Ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 200, -1, -1));

        etiqueta_Indicador_Correo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Correo.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Correo.setText("*");
        add(etiqueta_Indicador_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 260, 20, -1));

        etiqueta_Indicador_RUC.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_RUC.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_RUC.setText("*");
        add(etiqueta_Indicador_RUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 160, -1, -1));

        etiqueta_Indicador_Contacto.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Contacto.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Contacto.setText("*");
        add(etiqueta_Indicador_Contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        etiqueta_Indicador_Modalidad.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Modalidad.setForeground(new java.awt.Color(198, 0, 0));
        etiqueta_Indicador_Modalidad.setText("*");
        add(etiqueta_Indicador_Modalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 630, -1, -1));

        boton_Agregar_Cliente.setBackground(new java.awt.Color(255, 255, 255));
        boton_Agregar_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        boton_Agregar_Cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(boton_Agregar_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 156, 40, 30));

        combo_Cliente_Cotizacion.setEditable(false);
        combo_Cliente_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        combo_Cliente_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combo_Cliente_Cotizacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(combo_Cliente_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 230, 22));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Emite:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, -1));

        campo_Emisor_Cotizacion.setEditable(false);
        campo_Emisor_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        campo_Emisor_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Emisor_Cotizacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Emisor_Cotizacion.setMaximumSize(new java.awt.Dimension(2, 20));
        campo_Emisor_Cotizacion.setMinimumSize(new java.awt.Dimension(2, 20));
        campo_Emisor_Cotizacion.setPreferredSize(new java.awt.Dimension(2, 20));
        add(campo_Emisor_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 230, 22));

        boton_Cerrar_Sesion.setBackground(new java.awt.Color(255, 255, 255));
        boton_Cerrar_Sesion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Cerrar_Sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit-32.png"))); // NOI18N
        boton_Cerrar_Sesion.setText("Cerrar");
        boton_Cerrar_Sesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(boton_Cerrar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 120, 40));

        campo_Codigo_Cliente.setEditable(false);
        campo_Codigo_Cliente.setBackground(new java.awt.Color(255, 255, 255));
        campo_Codigo_Cliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Codigo_Cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(campo_Codigo_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 100, 22));

        etiqueta_Rol.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiqueta_Rol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(etiqueta_Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(1134, 20, 147, 20));

        etiqueta_Nombre_Usuario.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiqueta_Nombre_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        etiqueta_Nombre_Usuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        etiqueta_Nombre_Usuario.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(etiqueta_Nombre_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 180, 40));

        etiqueta_Indicador_Calendario.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Calendario.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Calendario.setText("*");
        add(etiqueta_Indicador_Calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 20, -1));

        valor_IVA.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        valor_IVA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                valor_IVAStateChanged(evt);
            }
        });
        valor_IVA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valor_IVAKeyTyped(evt);
            }
        });
        add(valor_IVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 660, 110, 23));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel20.setText("IVA %:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 665, -1, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Valor total", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 1030, 130));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo blanco.png"))); // NOI18N
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 180, 40));

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Informacion cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 1030, 200));

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 1030, 270));

        jLabel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1030, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void boton_Quitar_FilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Quitar_FilaActionPerformed
        try {
            this.modelo_Tabla_Datos_Cotizacion.removeRow(this.tabla_Productos_Cotizacion.getSelectedRow());
            calculo_Valores();
        } catch (Exception e1) {
        }
    }//GEN-LAST:event_boton_Quitar_FilaActionPerformed

    private void campo_Direccion_CotizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Direccion_CotizacionKeyTyped
        char c = evt.getKeyChar();
        if (c == evt.VK_SPACE && this.campo_Direccion_Cotizacion.getText().length() == 0) {
            evt.consume();
        } else if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < '0' || c > '9') && (c < '-' || c > '.') && c != evt.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_Direccion_CotizacionKeyTyped

    private void campo_RUC_CotizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_RUC_CotizacionKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9' || this.campo_RUC_Cotizacion.getText().length() >= 13) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_RUC_CotizacionKeyTyped

    private void campo_Ciudad_CotizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Ciudad_CotizacionKeyTyped
        char c = evt.getKeyChar();
        if (c == evt.VK_SPACE && this.campo_Ciudad_Cotizacion.getText().length() == 0) {
            evt.consume();
        } else if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && c != evt.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_Ciudad_CotizacionKeyTyped

    private void campo_Telefono_CotizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Telefono_CotizacionKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9' || this.campo_Telefono_Cotizacion.getText().length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_Telefono_CotizacionKeyTyped

    private void campo_Contacto_CotizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Contacto_CotizacionKeyTyped
        char c = evt.getKeyChar();
        if (c == evt.VK_SPACE && this.campo_Contacto_Cotizacion.getText().length() == 0) {
            evt.consume();
        } else if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && c != evt.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_Contacto_CotizacionKeyTyped

    private void campo_Correo_CotizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Correo_CotizacionKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < '0' || c > '9') && (c < '#' || c > '&') && (c < '-' || c > '/') && (c == evt.VK_SPACE || this.campo_Correo_Cotizacion.getText().contains("@"))) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_Correo_CotizacionKeyTyped

    private void tabla_Productos_CotizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_Productos_CotizacionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla_Productos_CotizacionKeyTyped

    private void boton_Nueva_CotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Nueva_CotizacionActionPerformed

    }//GEN-LAST:event_boton_Nueva_CotizacionActionPerformed

    private void campo_Modalidad_CotizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Modalidad_CotizacionKeyTyped
        char c = evt.getKeyChar();
        if (c == evt.VK_SPACE && this.campo_Modalidad_Cotizacion.getText().length() == 0) {
            evt.consume();
        } else if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < '0' || c > '9') && c != evt.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_Modalidad_CotizacionKeyTyped

    private void valor_IVAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_valor_IVAStateChanged

        if((Integer)this.valor_IVA.getValue() < 1){
            this.valor_IVA.setValue(1);
        }else if((Integer)this.valor_IVA.getValue() > 25){
            this.valor_IVA.setValue(25);
        }else{
            calculo_Valores();
        }
    }//GEN-LAST:event_valor_IVAStateChanged

    private void valor_IVAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valor_IVAKeyTyped

    }//GEN-LAST:event_valor_IVAKeyTyped
 
    public boolean etiquetas( ){
        boolean bandera = true;
        
        if( this.combo_Cliente_Cotizacion.getText().isEmpty() ){
            this.etiqueta_Indicador_Cliente.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Cliente.setVisible( false );
        }
        
        if( this.campo_Ciudad_Cotizacion.getText().isEmpty() ){
            this.etiqueta_Indicador_Ciudad.setVisible( true );
            bandera = false;
        }else{ 
           this.etiqueta_Indicador_Ciudad.setVisible( false );
        }
            
        if( this.campo_RUC_Cotizacion.getText().matches( "[0-9][0-9]{12}" ) ){
            this.etiqueta_Indicador_RUC.setVisible( false );
        }else if(this.campo_RUC_Cotizacion.getText().matches( "[0-9][0-9]{9}" ) ){
            this.etiqueta_Indicador_RUC.setVisible( false );
        }
        else{
            this.etiqueta_Indicador_RUC.setVisible( true );
            bandera = false;
        }
            
        if( this.campo_Direccion_Cotizacion.getText().isEmpty() ){ 
            this.etiqueta_Indicador_Direccion.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Direccion.setVisible( false );
        }
            
        if (this.campo_Telefono_Cotizacion.getText().matches("[0][1-9][0-9]{7}|[0][8-9][0-9]{8}")) {
            this.etiqueta_Indicador_Telefono.setVisible(false);
        } else {
            this.etiqueta_Indicador_Telefono.setVisible(true);
            bandera = false;
        }
        
        if (this.calendario_Cotizacion.getDate() == null) {
            this.etiqueta_Indicador_Calendario.setVisible(bandera);
            bandera = false;
        }else{
            this.etiqueta_Indicador_Calendario.setVisible(false);
        }
        
        if( this.campo_Correo_Cotizacion.getText().matches( "[a-zA-Z_\\d]+@[a-zA-Z]+(\\.[a-zA-Z]*)+" )){  
            this.etiqueta_Indicador_Correo.setVisible( false );
        }else{
            this.etiqueta_Indicador_Correo.setVisible( true );
            bandera = false;
        }
            
        if( this.campo_Contacto_Cotizacion.getText().isEmpty() ){
            this.etiqueta_Indicador_Contacto.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Contacto.setVisible( false );
        }
        
        if( this.campo_Modalidad_Cotizacion.getText().isEmpty() ){
            this.etiqueta_Indicador_Modalidad.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Modalidad.setVisible( false );
        }
        return bandera;
    }
    
    public String[] evaluar_Tabla() {
        DefaultTableModel modelo_Tabla_Cotizacion = (DefaultTableModel) this.tabla_Productos_Cotizacion.getModel();
        String[] valores = new String[6];

        for (int i = 0; i < modelo_Tabla_Cotizacion.getRowCount(); i++) {
            valores[0] = modelo_Tabla_Cotizacion.getValueAt(i, 0) + ";" + valores[0];
            valores[1] = modelo_Tabla_Cotizacion.getValueAt(i, 1) + ";" + valores[1];
            valores[2] = modelo_Tabla_Cotizacion.getValueAt(i, 2) + ";" + valores[2];
            valores[3] = modelo_Tabla_Cotizacion.getValueAt(i, 3) + ";" + valores[3];
            valores[4] = modelo_Tabla_Cotizacion.getValueAt(i, 4) + ";" + valores[4];
        }
        return valores;
    }

    public void limpiar_Valores() {
        this.campo_Subtotal_Cotizacion.setText("");
        this.campo_IVA_Cotizacion.setText("");
        this.campo_Total_Cotizacion.setText("");
        this.campo_Modalidad_Cotizacion.setText("");
        this.valor_IVA.setValue(12);
    }
    
    public void limpiar_Tabla() {
        DefaultTableModel modelo_Tabla_Cotizacion = (DefaultTableModel) this.tabla_Productos_Cotizacion.getModel();
        modelo_Tabla_Cotizacion.setRowCount(0);
    }

    public void botones(boolean bandera1, boolean bandera2, boolean bandera3, boolean bandera4, boolean bandera5, boolean bandera6) {
        this.boton_Guardar_Cotizacion.setEnabled(bandera1);
        this.boton_Agregar_Cliente.setEnabled(bandera1);
        this.boton_Nueva_Cotizacion.setEnabled(bandera2);
        this.boton_Modificar_Cotizacion.setEnabled(bandera3);
        this.boton_Generar_Cotizacion.setEnabled(bandera4);
        this.boton_Agregar_Fila.setEnabled(bandera6);
        this.boton_Quitar_Fila.setEnabled(bandera6);
        this.valor_IVA.setEnabled(bandera6);
    }
    
    public void calculo_Valores() {
        try {
            double valor_Subtotal = 0;
            for (int i = 0; i < this.modelo_Tabla_Datos_Cotizacion.getRowCount(); i++) {
                valor_Subtotal = valor_Subtotal + (double) this.modelo_Tabla_Datos_Cotizacion.getValueAt(i, 4);
            }
            this.campo_Subtotal_Cotizacion.setText(this.formato_Numero.format(valor_Subtotal));
            this.campo_IVA_Cotizacion.setText(this.formato_Numero.format(valor_Subtotal * (Integer)this.valor_IVA.getValue()/100));
            this.campo_Total_Cotizacion.setText(this.formato_Numero.format(Double.valueOf(this.campo_IVA_Cotizacion.getText()) + valor_Subtotal));
        } catch (Exception e) {
        }
    }

    public String calendario_Fecha() {
        Date fecha;
        fecha = (Date) this.calendario_Cotizacion.getDate();
        return new SimpleDateFormat("yyyy-MM-dd").format(fecha);
    }

    public void valores_Tabla_Cotizacion(Cotizacion lista_Cotizacion, Cliente cliente) {
        this.modelo_Tabla_Datos_Cotizacion.setRowCount(0);

        String[] cantidad = lista_Cotizacion.getCantidad().split(";");
        String[] codigo = lista_Cotizacion.getCodigo().split(";");
        String[] descripcion = lista_Cotizacion.getDescripcion().split(";");
        String[] v_Unitario = lista_Cotizacion.getV_Unitario().split(";");
        String[] v_Total = lista_Cotizacion.getV_Total().split(";");

        for (int i = 0; i < codigo.length - 1; i++) {
            Object[] valores_Tabla = {cantidad[i], codigo[i], descripcion[i], Double.parseDouble(v_Unitario[i]), Double.parseDouble(v_Total[i])};
            this.modelo_Tabla_Datos_Cotizacion.addRow(valores_Tabla);
        }

        this.valores_Clientes(cliente.getCodigo_Cliente(), cliente.getCliente(), cliente.getDireccion(), cliente.getTelefono(), cliente.getCorreo(), cliente.getRUC(), cliente.getCiudad(), cliente.getPersona_Contacto(), lista_Cotizacion.getEmisor(), "");
        this.valores_Cotizacion(lista_Cotizacion.getCliente(), lista_Cotizacion.getV_Subtotal(), lista_Cotizacion.getIVA(), lista_Cotizacion.getValor_Total(), lista_Cotizacion.getTipo_Pago(), lista_Cotizacion.getNo_Cotizacion());
    }
    
    public void valores_Clientes(String codigo_Cliente, String cliente, String direccion, String telefono, String correo, String RUC, String ciudad, String persona_Contacto, String nombre, String apellido) {
        this.campo_Codigo_Cliente.setText(codigo_Cliente);
        this.combo_Cliente_Cotizacion.setText(cliente);
        this.campo_Direccion_Cotizacion.setText(direccion);
        this.campo_Telefono_Cotizacion.setText(telefono);
        this.campo_Correo_Cotizacion.setText(correo);
        this.campo_RUC_Cotizacion.setText(RUC);
        this.campo_Ciudad_Cotizacion.setText(ciudad);
        this.campo_Contacto_Cotizacion.setText(persona_Contacto);
        this.campo_Emisor_Cotizacion.setText(nombre + " " + apellido);
    }

    public void valores_Cotizacion(String cliente, double subtotal, double IVA, double valor_Total, String modalidad, String no_Cotizacion) {
        this.campo_Subtotal_Cotizacion.setText(String.valueOf(subtotal));
        this.campo_IVA_Cotizacion.setText(String.valueOf(IVA));
        this.campo_Total_Cotizacion.setText(String.valueOf(valor_Total));
        this.campo_Modalidad_Cotizacion.setText(modalidad);
        this.etiqueta_No_Cotizacion.setText(no_Cotizacion);
        this.valor_IVA.setValue((int)((IVA/subtotal)*100));
    }
    
    public void limpiar_Etiquetas() {
        this.etiqueta_Indicador_Cliente.setVisible(false);
        this.etiqueta_Indicador_Ciudad.setVisible(false);
        this.etiqueta_Indicador_RUC.setVisible(false);
        this.etiqueta_Indicador_Direccion.setVisible(false);
        this.etiqueta_Indicador_Telefono.setVisible(false);
        this.etiqueta_Indicador_Correo.setVisible(false);
        this.etiqueta_Indicador_Contacto.setVisible(false);
        this.etiqueta_Indicador_Modalidad.setVisible(false);
    }
    
    public void habilitar_Rol(boolean[] bandera) {
        this.boton_Nueva_Cotizacion.setVisible(bandera[0]);
        this.boton_Guardar_Cotizacion.setVisible(bandera[1]);
        this.boton_Modificar_Cotizacion.setVisible(bandera[2]);
        this.boton_Generar_Cotizacion.setVisible(bandera[3]);
        this.boton_Agregar_Cliente.setVisible(bandera[4]);
        this.boton_Agregar_Fila.setVisible(bandera[5]);
        this.boton_Quitar_Fila.setVisible(bandera[6]);
    }
    
    public void set_Usuario(Usuario usuario, String rol){
        this.etiqueta_Nombre_Usuario.setText(usuario.getNombre() + " " + usuario.getApellido());
        this.etiqueta_Rol.setText(rol);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton boton_Agregar_Cliente;
    public javax.swing.JButton boton_Agregar_Fila;
    public javax.swing.JButton boton_Buscar_Cotizacion;
    public javax.swing.JButton boton_Cerrar_Sesion;
    public javax.swing.JButton boton_Generar_Cotizacion;
    public javax.swing.JButton boton_Guardar_Cotizacion;
    public javax.swing.JButton boton_Modificar_Cotizacion;
    public javax.swing.JButton boton_Nueva_Cotizacion;
    public javax.swing.JButton boton_Quitar_Fila;
    public com.toedter.calendar.JDateChooser calendario_Cotizacion;
    public javax.swing.JTextField campo_Ciudad_Cotizacion;
    public javax.swing.JTextField campo_Codigo_Cliente;
    public javax.swing.JTextField campo_Contacto_Cotizacion;
    public javax.swing.JTextField campo_Correo_Cotizacion;
    public javax.swing.JTextField campo_Direccion_Cotizacion;
    public javax.swing.JTextField campo_Emisor_Cotizacion;
    public javax.swing.JTextField campo_IVA_Cotizacion;
    public javax.swing.JTextField campo_Modalidad_Cotizacion;
    public javax.swing.JTextField campo_RUC_Cotizacion;
    public javax.swing.JTextField campo_Subtotal_Cotizacion;
    public javax.swing.JTextField campo_Telefono_Cotizacion;
    public javax.swing.JTextField campo_Total_Cotizacion;
    public javax.swing.JTextField combo_Cliente_Cotizacion;
    private javax.swing.JLabel etiqueta_Indicador_Calendario;
    private javax.swing.JLabel etiqueta_Indicador_Ciudad;
    private javax.swing.JLabel etiqueta_Indicador_Cliente;
    private javax.swing.JLabel etiqueta_Indicador_Contacto;
    private javax.swing.JLabel etiqueta_Indicador_Correo;
    private javax.swing.JLabel etiqueta_Indicador_Direccion;
    private javax.swing.JLabel etiqueta_Indicador_Modalidad;
    private javax.swing.JLabel etiqueta_Indicador_RUC;
    private javax.swing.JLabel etiqueta_Indicador_Telefono;
    public javax.swing.JLabel etiqueta_No_Cotizacion;
    public javax.swing.JLabel etiqueta_Nombre_Usuario;
    public javax.swing.JLabel etiqueta_Rol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JTable tabla_Productos_Cotizacion;
    public javax.swing.JSpinner valor_IVA;
    // End of variables declaration//GEN-END:variables
}
