/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Proveedor;

import Controlador.PlaceHolder_Textos;
import Modelo.Usuario;

/**
 *
 * @author David
 */
public class Panel_Proveedor extends javax.swing.JPanel {
    PlaceHolder_Textos textos_Place;
    /**
     * Creates new form Panel_Proveedor
     */
    public Panel_Proveedor() {
        initComponents();
        this.grupo_Botones.add(this.radio_Cedula);
        this.grupo_Botones.add(this.radio_RUC);
        this.grupo_Botones_Telefono.add(this.radio_Convencional);
        this.grupo_Botones_Telefono.add(this.radio_Celular);
        this.campo_RUC.setEditable(false);
        this.campo_Telefono.setEditable(false);
        this.textos_Place = new PlaceHolder_Textos("Nombre proveedor", this.combo_Proveedor);
        this.textos_Place = new PlaceHolder_Textos("172004xxxxxxx", this.campo_RUC);
        this.textos_Place = new PlaceHolder_Textos("Av principal OE7-489", this.campo_Direccion);
        this.textos_Place = new PlaceHolder_Textos("023005698", this.campo_Telefono);
        this.textos_Place = new PlaceHolder_Textos("empresa@dominio.com", this.campo_Correo);
        this.textos_Place = new PlaceHolder_Textos("Productos de venta", this.caja_Productos);
        this.etiqueta_Indicador_Proveedor.setVisible( false );
        this.etiqueta_Indicador_RUC.setVisible( false );
        this.etiqueta_Indicador_Direccion.setVisible( false );
        this.etiqueta_Indicador_Telefono.setVisible( false );  
        this.etiqueta_Indicador_Correo.setVisible( false );
        this.etiqueta_Indicador_Producto.setVisible( false );
        this.etiqueta_Correccion_RUC.setVisible(false);
        this.etiqueta_Correccion_Correo.setVisible(false);
        this.boton_Modificar.setEnabled( false );
        this.boton_Eliminar.setEnabled( false );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_Botones = new javax.swing.ButtonGroup();
        grupo_Botones_Telefono = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        boton_Nuevo_Proveedor = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        boton_Guardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        boton_Modificar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        boton_Eliminar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        boton_Reporte_Proveedor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        boton_Buscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        campo_RUC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campo_Direccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campo_Correo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campo_Telefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        caja_Productos = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        etiqueta_Indicador_RUC = new javax.swing.JLabel();
        etiqueta_Indicador_Direccion = new javax.swing.JLabel();
        etiqueta_Indicador_Correo = new javax.swing.JLabel();
        etiqueta_Indicador_Telefono = new javax.swing.JLabel();
        etiqueta_Indicador_Producto = new javax.swing.JLabel();
        combo_Proveedor = new javax.swing.JTextField();
        etiqueta_Indicador_Proveedor = new javax.swing.JLabel();
        boton_Cerrar_Sesion = new javax.swing.JButton();
        radio_RUC = new javax.swing.JRadioButton();
        radio_Cedula = new javax.swing.JRadioButton();
        radio_Convencional = new javax.swing.JRadioButton();
        radio_Celular = new javax.swing.JRadioButton();
        etiqueta_Correccion_Correo = new javax.swing.JLabel();
        etiqueta_Correccion_RUC = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        etiqueta_Rol = new javax.swing.JLabel();
        etiqueta_Nombre_Usuario = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.activeCaption);
        setMaximumSize(new java.awt.Dimension(1400, 800));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setPreferredSize(new java.awt.Dimension(1400, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        boton_Nuevo_Proveedor.setBackground(new java.awt.Color(255, 255, 255));
        boton_Nuevo_Proveedor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Nuevo_Proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-archivo.png"))); // NOI18N
        boton_Nuevo_Proveedor.setText("Nuevo");
        boton_Nuevo_Proveedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Nuevo_Proveedor.setFocusable(false);
        boton_Nuevo_Proveedor.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Nuevo_Proveedor.setMinimumSize(new java.awt.Dimension(100, 37));
        boton_Nuevo_Proveedor.setPreferredSize(new java.awt.Dimension(100, 37));
        boton_Nuevo_Proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Nuevo_ProveedorActionPerformed(evt);
            }
        });
        jToolBar1.add(boton_Nuevo_Proveedor);
        jToolBar1.add(jSeparator4);

        boton_Guardar.setBackground(java.awt.Color.white);
        boton_Guardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton-anadir-usuario (1).png"))); // NOI18N
        boton_Guardar.setText("Guardar");
        boton_Guardar.setToolTipText(" Agregar");
        boton_Guardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Guardar.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Guardar.setMinimumSize(new java.awt.Dimension(60, 37));
        boton_Guardar.setPreferredSize(new java.awt.Dimension(60, 37));
        boton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_GuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(boton_Guardar);
        jToolBar1.add(jSeparator1);

        boton_Modificar.setBackground(java.awt.Color.white);
        boton_Modificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar-documento.png"))); // NOI18N
        boton_Modificar.setText("Modificar");
        boton_Modificar.setToolTipText(" Editar");
        boton_Modificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Modificar.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Modificar.setMinimumSize(new java.awt.Dimension(100, 37));
        boton_Modificar.setPreferredSize(new java.awt.Dimension(60, 37));
        jToolBar1.add(boton_Modificar);
        jToolBar1.add(jSeparator2);

        boton_Eliminar.setBackground(java.awt.Color.white);
        boton_Eliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton-eliminar.png"))); // NOI18N
        boton_Eliminar.setText("Eliminar");
        boton_Eliminar.setToolTipText("Eliminar");
        boton_Eliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Eliminar.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Eliminar.setMinimumSize(new java.awt.Dimension(100, 37));
        boton_Eliminar.setPreferredSize(new java.awt.Dimension(60, 37));
        jToolBar1.add(boton_Eliminar);
        jToolBar1.add(jSeparator3);

        boton_Reporte_Proveedor.setBackground(new java.awt.Color(255, 255, 255));
        boton_Reporte_Proveedor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Reporte_Proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportar.png"))); // NOI18N
        boton_Reporte_Proveedor.setText("Reporte");
        boton_Reporte_Proveedor.setToolTipText("Reporte");
        boton_Reporte_Proveedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Reporte_Proveedor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Reporte_Proveedor.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Reporte_Proveedor.setMinimumSize(new java.awt.Dimension(100, 37));
        boton_Reporte_Proveedor.setPreferredSize(new java.awt.Dimension(100, 37));
        jToolBar1.add(boton_Reporte_Proveedor);

        add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Nombre comercial:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        boton_Buscar.setBackground(java.awt.Color.white);
        boton_Buscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        boton_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar-en-carpeta.png"))); // NOI18N
        boton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_BuscarActionPerformed(evt);
            }
        });
        add(boton_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 40, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("R.U.C/ CI:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        campo_RUC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_RUC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_RUC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_RUCKeyTyped(evt);
            }
        });
        add(campo_RUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 259, 22));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Direccion:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        campo_Direccion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Direccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_DireccionKeyTyped(evt);
            }
        });
        add(campo_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 530, 22));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Correo:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        campo_Correo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Correo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_CorreoKeyTyped(evt);
            }
        });
        add(campo_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 240, 22));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Telefono");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        campo_Telefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Telefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_TelefonoKeyTyped(evt);
            }
        });
        add(campo_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 180, 22));

        caja_Productos.setColumns(20);
        caja_Productos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        caja_Productos.setRows(5);
        caja_Productos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        caja_Productos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_ProductosKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(caja_Productos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 400, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Productos:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, -1, -1));

        etiqueta_Indicador_RUC.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_RUC.setForeground(new java.awt.Color(198, 0, 0));
        etiqueta_Indicador_RUC.setText("*");
        add(etiqueta_Indicador_RUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        etiqueta_Indicador_Direccion.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Direccion.setForeground(new java.awt.Color(198, 0, 0));
        etiqueta_Indicador_Direccion.setText("*");
        add(etiqueta_Indicador_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, -1, -1));

        etiqueta_Indicador_Correo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Correo.setForeground(new java.awt.Color(198, 0, 0));
        etiqueta_Indicador_Correo.setText("*");
        add(etiqueta_Indicador_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, -1, -1));

        etiqueta_Indicador_Telefono.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Telefono.setForeground(new java.awt.Color(198, 0, 0));
        etiqueta_Indicador_Telefono.setText("*");
        add(etiqueta_Indicador_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, -1, -1));

        etiqueta_Indicador_Producto.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Producto.setForeground(new java.awt.Color(195, 0, 0));
        etiqueta_Indicador_Producto.setText("*");
        add(etiqueta_Indicador_Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, -1, -1));

        combo_Proveedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combo_Proveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        combo_Proveedor.setDisabledTextColor(new java.awt.Color(51, 0, 255));
        combo_Proveedor.setMaximumSize(new java.awt.Dimension(2, 20));
        combo_Proveedor.setMinimumSize(new java.awt.Dimension(2, 20));
        combo_Proveedor.setPreferredSize(new java.awt.Dimension(2, 20));
        add(combo_Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 310, 22));

        etiqueta_Indicador_Proveedor.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Proveedor.setForeground(new java.awt.Color(198, 0, 0));
        etiqueta_Indicador_Proveedor.setText("*");
        add(etiqueta_Indicador_Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, -1, -1));

        boton_Cerrar_Sesion.setBackground(new java.awt.Color(255, 255, 255));
        boton_Cerrar_Sesion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Cerrar_Sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit-32.png"))); // NOI18N
        boton_Cerrar_Sesion.setText("Cerrar");
        boton_Cerrar_Sesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(boton_Cerrar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 120, 40));

        radio_RUC.setBackground(new java.awt.Color(255, 255, 255));
        radio_RUC.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        radio_RUC.setText("RUC");
        radio_RUC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        radio_RUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_RUCActionPerformed(evt);
            }
        });
        add(radio_RUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, -1));

        radio_Cedula.setBackground(new java.awt.Color(255, 255, 255));
        radio_Cedula.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        radio_Cedula.setText("Cedula");
        radio_Cedula.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        radio_Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_CedulaActionPerformed(evt);
            }
        });
        add(radio_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, -1, -1));

        radio_Convencional.setBackground(new java.awt.Color(255, 255, 255));
        radio_Convencional.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        radio_Convencional.setText("Convencional");
        radio_Convencional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_ConvencionalActionPerformed(evt);
            }
        });
        add(radio_Convencional, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, -1, -1));

        radio_Celular.setBackground(new java.awt.Color(255, 255, 255));
        radio_Celular.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        radio_Celular.setText("Celular");
        radio_Celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_CelularActionPerformed(evt);
            }
        });
        add(radio_Celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, -1, -1));

        etiqueta_Correccion_Correo.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        etiqueta_Correccion_Correo.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Correccion_Correo.setText("El Correo ya se encuentra registrado para otro cliente");
        add(etiqueta_Correccion_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 352, 310, -1));

        etiqueta_Correccion_RUC.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        etiqueta_Correccion_RUC.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Correccion_RUC.setText("El RUC/CI ya se encuentra registrado para otro cliente");
        add(etiqueta_Correccion_RUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 235, 310, -1));

        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "DATOS PROVEEDOR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 18))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 1270, 640));

        etiqueta_Rol.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiqueta_Rol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(etiqueta_Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(1134, 20, 147, 20));

        etiqueta_Nombre_Usuario.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiqueta_Nombre_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        etiqueta_Nombre_Usuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        etiqueta_Nombre_Usuario.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(etiqueta_Nombre_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 180, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo blanco.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 180, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void boton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_BuscarActionPerformed

    private void boton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_GuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_GuardarActionPerformed

    private void campo_RUCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_RUCKeyTyped
        char c = evt.getKeyChar();
        if (this.radio_RUC.isSelected()) {
            if (c < '0' || c > '9' || this.campo_RUC.getText().length() >= 13) {
                evt.consume();
            }
        }
        
        if (this.radio_Cedula.isSelected()) {
            if (c < '0' || c > '9' || this.campo_RUC.getText().length() >= 10) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_campo_RUCKeyTyped

    private void campo_DireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_DireccionKeyTyped
        char c = evt.getKeyChar();
        if( c == evt.VK_SPACE && this.campo_Direccion.getText().length() == 0 ) evt.consume();
        else if(  ( c < 'a' || c > 'z' ) && ( c < 'A' || c>'Z' ) && ( c < '0' || c > '9' ) && ( c < '-' || c > '.' ) && c != evt.VK_SPACE ){
            evt.consume();
        }
    }//GEN-LAST:event_campo_DireccionKeyTyped

    private void campo_CorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_CorreoKeyTyped
        char c = evt.getKeyChar();
        if ( ( c < 'a' || c > 'z' ) && ( c < 'A' || c >'Z' ) && ( c < '0'  || c > '9' ) && ( c < '#' || c > '&' ) && ( c < '-' || c > '/' ) &&  (  c == evt.VK_SPACE || this.campo_Correo.getText().contains( "@" ) ) ) evt.consume();
    }//GEN-LAST:event_campo_CorreoKeyTyped

    private void campo_TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_TelefonoKeyTyped
        char c = evt.getKeyChar();
        
        if (this.radio_Convencional.isSelected()) {
            if (c < '0' || c > '9' || this.campo_Telefono.getText().length() >= 9) {
                evt.consume();
            }
        }
        
        if (this.radio_Celular.isSelected()) {
            if (c < '0' || c > '9' || this.campo_Telefono.getText().length() >= 10) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_campo_TelefonoKeyTyped

    private void caja_ProductosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_ProductosKeyTyped
        char c = evt.getKeyChar();
        if( c == evt.VK_SPACE && this.caja_Productos.getText().length() == 0 ) evt.consume();
        else if( ( c < 'a' || c > 'z' ) && ( c < 'A' || c>'Z' ) && ( c < '0' || c > '9' ) && c != evt.VK_SPACE ){
            evt.consume();
        }
    }//GEN-LAST:event_caja_ProductosKeyTyped

    private void boton_Nuevo_ProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Nuevo_ProveedorActionPerformed
        limpiar_Campos();
        this.botones(true, true, false, false, true, true);
        this.etiqueta_Indicador_Proveedor.setVisible( false );
        this.etiqueta_Indicador_RUC.setVisible( false );
        this.etiqueta_Indicador_Direccion.setVisible( false );
        this.etiqueta_Indicador_Telefono.setVisible( false );
        this.etiqueta_Indicador_Correo.setVisible( false );
        this.etiqueta_Indicador_Producto.setVisible( false );
        this.etiqueta_Correccion_RUC.setVisible(false);
        this.etiqueta_Correccion_Correo.setVisible(false);
        
    }//GEN-LAST:event_boton_Nuevo_ProveedorActionPerformed

    private void radio_RUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_RUCActionPerformed
        this.campo_RUC.setEditable(true);
        this.campo_RUC.setText("");
    }//GEN-LAST:event_radio_RUCActionPerformed

    private void radio_CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_CedulaActionPerformed
        this.campo_RUC.setEditable(true);
        this.campo_RUC.setText("");
    }//GEN-LAST:event_radio_CedulaActionPerformed

    private void radio_ConvencionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_ConvencionalActionPerformed
        this.campo_Telefono.setEditable(true);
        this.campo_Telefono.setText("");
    }//GEN-LAST:event_radio_ConvencionalActionPerformed

    private void radio_CelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_CelularActionPerformed
        this.campo_Telefono.setEditable(true);
        this.campo_Telefono.setText("");
    }//GEN-LAST:event_radio_CelularActionPerformed

    public boolean etiquetas( boolean bandera ){
        
        if( this.combo_Proveedor.getText().isEmpty() ){
            this.etiqueta_Indicador_Proveedor.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Proveedor.setVisible( false );
        }
            
        if( this.campo_RUC.getText().matches( "[0-9][0-9]{12}" ) && this.radio_RUC.isSelected() ){
            this.etiqueta_Indicador_RUC.setVisible( false );
        }else if(this.campo_RUC.getText().matches( "[0-9][0-9]{9}" ) && this.radio_Cedula.isSelected()){
            this.etiqueta_Indicador_RUC.setVisible( false );
        }
        else{
            this.etiqueta_Indicador_RUC.setVisible( true );
            bandera = false;
        }
            
        if( this.campo_Direccion.getText().isEmpty() ){ 
            this.etiqueta_Indicador_Direccion.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Direccion.setVisible( false );
        }
            
        if( this.campo_Telefono.getText().matches( "[0][1-9][0-9]{7}" ) && this.radio_Convencional.isSelected() ){
            this.etiqueta_Indicador_Telefono.setVisible( false );
        }else if(this.campo_Telefono.getText().matches( "[0-9][0-9]{9}" ) && this.radio_Celular.isSelected()){
            this.etiqueta_Indicador_Telefono.setVisible( false );
        }
        else{
            this.etiqueta_Indicador_Telefono.setVisible( true );
            bandera = false;
        } 
        
        if( this.campo_Correo.getText().matches( "[a-zA-Z_\\d]+@[a-zA-Z]+(\\.[a-zA-Z]*)+" )){  
            this.etiqueta_Indicador_Correo.setVisible( false );
        }else{
            this.etiqueta_Indicador_Correo.setVisible( true );
            bandera = false;
        }
            
        if( this.caja_Productos.getText().isEmpty() ){
            this.etiqueta_Indicador_Producto.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Producto.setVisible( false );
        }
        return bandera;
    }
    
    public void limpiar_Campos(){
        this.combo_Proveedor.setText("");
        this.campo_Correo.setText( "" );
        this.campo_Direccion.setText( "" );
        this.campo_RUC.setText( "" );
        this.grupo_Botones_Telefono.clearSelection();
        this.campo_Telefono.setText( "" );
        this.caja_Productos.setText( "" );
        this.grupo_Botones.clearSelection();
        this.campo_RUC.setEditable(false);
        this.campo_Telefono.setEditable(false);
        this.etiqueta_Correccion_RUC.setVisible(false);
        this.etiqueta_Correccion_Correo.setVisible(false);
    }
    
    public void botones( boolean bandera1, boolean bandera2, boolean bandera3, boolean bandera4, boolean bandera5, boolean bandera6  ){
        this.boton_Guardar.setEnabled(bandera1);
        this.boton_Nuevo_Proveedor.setEnabled(bandera2);
        this.boton_Modificar.setEnabled(bandera3);
        this.boton_Eliminar.setEnabled(bandera4);
        this.boton_Reporte_Proveedor.setEnabled(bandera6);
    }
       
    public void setCampos( String proveedor, String direccion, String RUC, String telefono, String correo, String producto){
        this.botones(false, true, true, true, false, false);
        this.combo_Proveedor.setText(proveedor);
        this.campo_Direccion.setText(direccion);
        this.campo_RUC.setText(RUC);
        this.campo_Telefono.setText(telefono);
        this.campo_Correo.setText(correo);
        this.caja_Productos.setText(producto);
    }
    
    public void campos_Busqueda() {
        this.campo_RUC.setEditable(true);
        this.campo_Telefono.setEditable(true);

        if (this.campo_RUC.getText().length() == 10) {
            this.radio_Cedula.setSelected(true);
        } else if (this.campo_RUC.getText().length() == 13) {
            this.radio_RUC.setSelected(true);
        }

        if (this.campo_Telefono.getText().length() == 9) {
            this.radio_Convencional.setSelected(true);
        } else if (this.campo_Telefono.getText().length() == 10) {
            this.radio_Celular.setSelected(true);
        }
    }
    
    public void set_Usuario(Usuario usuario, String rol){
        this.etiqueta_Nombre_Usuario.setText(usuario.getNombre() + " " + usuario.getApellido());
        this.etiqueta_Rol.setText(rol);
    }
    
    public void correccion_Campos(String valor){
        if(valor.equals(this.campo_RUC.getText())){
            this.etiqueta_Correccion_RUC.setVisible(true);
        }
        
        if(valor.equals(this.campo_Correo.getText())){
            this.etiqueta_Correccion_Correo.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton boton_Buscar;
    public javax.swing.JButton boton_Cerrar_Sesion;
    public javax.swing.JButton boton_Eliminar;
    public javax.swing.JButton boton_Guardar;
    public javax.swing.JButton boton_Modificar;
    public javax.swing.JButton boton_Nuevo_Proveedor;
    public javax.swing.JButton boton_Reporte_Proveedor;
    public javax.swing.JTextArea caja_Productos;
    public javax.swing.JTextField campo_Correo;
    public javax.swing.JTextField campo_Direccion;
    public javax.swing.JTextField campo_RUC;
    public javax.swing.JTextField campo_Telefono;
    public javax.swing.JTextField combo_Proveedor;
    private javax.swing.JLabel etiqueta_Correccion_Correo;
    private javax.swing.JLabel etiqueta_Correccion_RUC;
    private javax.swing.JLabel etiqueta_Indicador_Correo;
    private javax.swing.JLabel etiqueta_Indicador_Direccion;
    private javax.swing.JLabel etiqueta_Indicador_Producto;
    private javax.swing.JLabel etiqueta_Indicador_Proveedor;
    private javax.swing.JLabel etiqueta_Indicador_RUC;
    private javax.swing.JLabel etiqueta_Indicador_Telefono;
    public javax.swing.JLabel etiqueta_Nombre_Usuario;
    public javax.swing.JLabel etiqueta_Rol;
    private javax.swing.ButtonGroup grupo_Botones;
    private javax.swing.ButtonGroup grupo_Botones_Telefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JRadioButton radio_Cedula;
    private javax.swing.JRadioButton radio_Celular;
    private javax.swing.JRadioButton radio_Convencional;
    private javax.swing.JRadioButton radio_RUC;
    // End of variables declaration//GEN-END:variables
}
